name: Setup Node
description: "Setup Node.js environment and install dependencies"

inputs:
  node-version:
    description: "Node.js version to setup"
    required: false
    default: "20"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
