/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliCloudLoginResponse
 */
export interface AliCloudLoginResponse {
    /**
     * Accessor for the client token.
     * @type {string}
     * @memberof AliCloudLoginResponse
     */
    accessor?: string;
    /**
     * Token issued by Vault for the authenticated client.
     * @type {string}
     * @memberof AliCloudLoginResponse
     */
    client_token?: string;
    /**
     * Entity ID associated with the token.
     * @type {string}
     * @memberof AliCloudLoginResponse
     */
    entity_id?: string;
    /**
     * Lease duration in seconds.
     * @type {number}
     * @memberof AliCloudLoginResponse
     */
    lease_duration?: number;
    /**
     * Metadata associated with the token.
     * @type {object}
     * @memberof AliCloudLoginResponse
     */
    metadata?: object;
    /**
     * MFA requirement information.
     * @type {object}
     * @memberof AliCloudLoginResponse
     */
    mfa_requirement?: object;
    /**
     * Number of uses remaining for the token.
     * @type {number}
     * @memberof AliCloudLoginResponse
     */
    num_uses?: number;
    /**
     * Whether the token is an orphan.
     * @type {boolean}
     * @memberof AliCloudLoginResponse
     */
    orphan?: boolean;
    /**
     * List of policies associated with the token.
     * @type {Array<string>}
     * @memberof AliCloudLoginResponse
     */
    policies?: Array<string>;
    /**
     * Whether the token is renewable.
     * @type {boolean}
     * @memberof AliCloudLoginResponse
     */
    renewable?: boolean;
    /**
     * List of token policies.
     * @type {Array<string>}
     * @memberof AliCloudLoginResponse
     */
    token_policies?: Array<string>;
    /**
     * Type of the token.
     * @type {string}
     * @memberof AliCloudLoginResponse
     */
    token_type?: string;
}

/**
 * Check if a given object implements the AliCloudLoginResponse interface.
 */
export function instanceOfAliCloudLoginResponse(value: object): value is AliCloudLoginResponse {
    return true;
}

export function AliCloudLoginResponseFromJSON(json: any): AliCloudLoginResponse {
    return AliCloudLoginResponseFromJSONTyped(json, false);
}

export function AliCloudLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliCloudLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessor': json['accessor'] == null ? undefined : json['accessor'],
        'client_token': json['client_token'] == null ? undefined : json['client_token'],
        'entity_id': json['entity_id'] == null ? undefined : json['entity_id'],
        'lease_duration': json['lease_duration'] == null ? undefined : json['lease_duration'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'mfa_requirement': json['mfa_requirement'] == null ? undefined : json['mfa_requirement'],
        'num_uses': json['num_uses'] == null ? undefined : json['num_uses'],
        'orphan': json['orphan'] == null ? undefined : json['orphan'],
        'policies': json['policies'] == null ? undefined : json['policies'],
        'renewable': json['renewable'] == null ? undefined : json['renewable'],
        'token_policies': json['token_policies'] == null ? undefined : json['token_policies'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
    };
}

export function AliCloudLoginResponseToJSON(json: any): AliCloudLoginResponse {
    return AliCloudLoginResponseToJSONTyped(json, false);
}

export function AliCloudLoginResponseToJSONTyped(value?: AliCloudLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessor': value['accessor'],
        'client_token': value['client_token'],
        'entity_id': value['entity_id'],
        'lease_duration': value['lease_duration'],
        'metadata': value['metadata'],
        'mfa_requirement': value['mfa_requirement'],
        'num_uses': value['num_uses'],
        'orphan': value['orphan'],
        'policies': value['policies'],
        'renewable': value['renewable'],
        'token_policies': value['token_policies'],
        'token_type': value['token_type'],
    };
}

