/**
 * Copyright IBM Corp. 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppRoleWriteRoleRequest
 */
export interface AppRoleWriteRoleRequest {
    /**
     * The metadata to be tied to generated entity alias. This should be a list or map containing the metadata in key value pairs
     * @type {object}
     * @memberof AppRoleWriteRoleRequest
     */
    alias_metadata?: object;
    /**
     * Impose secret_id to be presented when logging in using this role. Defaults to 'true'.
     * @type {boolean}
     * @memberof AppRoleWriteRoleRequest
     */
    bind_secret_id?: boolean;
    /**
     * Use "secret_id_bound_cidrs" instead.
     * @type {Array<string>}
     * @memberof AppRoleWriteRoleRequest
     * @deprecated
     */
    bound_cidr_list?: Array<string>;
    /**
     * If set, the secret IDs generated using this role will be cluster local. This can only be set during role creation and once set, it can't be reset later.
     * @type {boolean}
     * @memberof AppRoleWriteRoleRequest
     */
    local_secret_ids?: boolean;
    /**
     * Use "token_period" instead. If this and "token_period" are both specified, only "token_period" will be used.
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     * @deprecated
     */
    period?: string;
    /**
     * Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
     * @type {Array<string>}
     * @memberof AppRoleWriteRoleRequest
     * @deprecated
     */
    policies?: Array<string>;
    /**
     * Identifier of the role. Defaults to a UUID.
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     */
    role_id?: string;
    /**
     * Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can perform the login operation.
     * @type {Array<string>}
     * @memberof AppRoleWriteRoleRequest
     */
    secret_id_bound_cidrs?: Array<string>;
    /**
     * Number of times a SecretID can access the role, after which the SecretID will expire. Defaults to 0 meaning that the the secret_id is of unlimited use.
     * @type {number}
     * @memberof AppRoleWriteRoleRequest
     */
    secret_id_num_uses?: number;
    /**
     * Duration in seconds after which the issued SecretID should expire. Defaults to 0, meaning no expiration.
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     */
    secret_id_ttl?: string;
    /**
     * Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
     * @type {Array<string>}
     * @memberof AppRoleWriteRoleRequest
     */
    token_bound_cidrs?: Array<string>;
    /**
     * If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     */
    token_explicit_max_ttl?: string;
    /**
     * The maximum lifetime of the generated token
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     */
    token_max_ttl?: string;
    /**
     * If true, the 'default' policy will not automatically be added to generated tokens
     * @type {boolean}
     * @memberof AppRoleWriteRoleRequest
     */
    token_no_default_policy?: boolean;
    /**
     * The maximum number of times a token may be used, a value of zero means unlimited
     * @type {number}
     * @memberof AppRoleWriteRoleRequest
     */
    token_num_uses?: number;
    /**
     * If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     */
    token_period?: string;
    /**
     * Comma-separated list of policies
     * @type {Array<string>}
     * @memberof AppRoleWriteRoleRequest
     */
    token_policies?: Array<string>;
    /**
     * The initial ttl of the token to generate
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     */
    token_ttl?: string;
    /**
     * The type of token to generate, service or batch
     * @type {string}
     * @memberof AppRoleWriteRoleRequest
     */
    token_type?: string;
}

/**
 * Check if a given object implements the AppRoleWriteRoleRequest interface.
 */
export function instanceOfAppRoleWriteRoleRequest(value: object): value is AppRoleWriteRoleRequest {
    return true;
}

export function AppRoleWriteRoleRequestFromJSON(json: any): AppRoleWriteRoleRequest {
    return AppRoleWriteRoleRequestFromJSONTyped(json, false);
}

export function AppRoleWriteRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoleWriteRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alias_metadata': json['alias_metadata'] == null ? undefined : json['alias_metadata'],
        'bind_secret_id': json['bind_secret_id'] == null ? undefined : json['bind_secret_id'],
        'bound_cidr_list': json['bound_cidr_list'] == null ? undefined : json['bound_cidr_list'],
        'local_secret_ids': json['local_secret_ids'] == null ? undefined : json['local_secret_ids'],
        'period': json['period'] == null ? undefined : json['period'],
        'policies': json['policies'] == null ? undefined : json['policies'],
        'role_id': json['role_id'] == null ? undefined : json['role_id'],
        'secret_id_bound_cidrs': json['secret_id_bound_cidrs'] == null ? undefined : json['secret_id_bound_cidrs'],
        'secret_id_num_uses': json['secret_id_num_uses'] == null ? undefined : json['secret_id_num_uses'],
        'secret_id_ttl': json['secret_id_ttl'] == null ? undefined : json['secret_id_ttl'],
        'token_bound_cidrs': json['token_bound_cidrs'] == null ? undefined : json['token_bound_cidrs'],
        'token_explicit_max_ttl': json['token_explicit_max_ttl'] == null ? undefined : json['token_explicit_max_ttl'],
        'token_max_ttl': json['token_max_ttl'] == null ? undefined : json['token_max_ttl'],
        'token_no_default_policy': json['token_no_default_policy'] == null ? undefined : json['token_no_default_policy'],
        'token_num_uses': json['token_num_uses'] == null ? undefined : json['token_num_uses'],
        'token_period': json['token_period'] == null ? undefined : json['token_period'],
        'token_policies': json['token_policies'] == null ? undefined : json['token_policies'],
        'token_ttl': json['token_ttl'] == null ? undefined : json['token_ttl'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
    };
}

export function AppRoleWriteRoleRequestToJSON(json: any): AppRoleWriteRoleRequest {
    return AppRoleWriteRoleRequestToJSONTyped(json, false);
}

export function AppRoleWriteRoleRequestToJSONTyped(value?: AppRoleWriteRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias_metadata': value['alias_metadata'],
        'bind_secret_id': value['bind_secret_id'],
        'bound_cidr_list': value['bound_cidr_list'],
        'local_secret_ids': value['local_secret_ids'],
        'period': value['period'],
        'policies': value['policies'],
        'role_id': value['role_id'],
        'secret_id_bound_cidrs': value['secret_id_bound_cidrs'],
        'secret_id_num_uses': value['secret_id_num_uses'],
        'secret_id_ttl': value['secret_id_ttl'],
        'token_bound_cidrs': value['token_bound_cidrs'],
        'token_explicit_max_ttl': value['token_explicit_max_ttl'],
        'token_max_ttl': value['token_max_ttl'],
        'token_no_default_policy': value['token_no_default_policy'],
        'token_num_uses': value['token_num_uses'],
        'token_period': value['token_period'],
        'token_policies': value['token_policies'],
        'token_ttl': value['token_ttl'],
        'token_type': value['token_type'],
    };
}

