/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwsGenerateStsCredentialsWithParametersResponse
 */
export interface AwsGenerateStsCredentialsWithParametersResponse {
    /**
     * AWS access key ID.
     * @type {string}
     * @memberof AwsGenerateStsCredentialsWithParametersResponse
     */
    access_key?: string;
    /**
     * ARN of the assumed role (only set for assumed_role credential type).
     * @type {string}
     * @memberof AwsGenerateStsCredentialsWithParametersResponse
     */
    arn?: string;
    /**
     * AWS secret access key.
     * @type {string}
     * @memberof AwsGenerateStsCredentialsWithParametersResponse
     */
    secret_key?: string;
    /**
     * AWS security token for STS credentials. Deprecated; use session_token.
     * @type {string}
     * @memberof AwsGenerateStsCredentialsWithParametersResponse
     */
    security_token?: string;
    /**
     * AWS session token for STS credentials.
     * @type {string}
     * @memberof AwsGenerateStsCredentialsWithParametersResponse
     */
    session_token?: string;
    /**
     * TTL of the credentials in seconds (only set for STS credential types).
     * @type {number}
     * @memberof AwsGenerateStsCredentialsWithParametersResponse
     */
    ttl?: number;
}

/**
 * Check if a given object implements the AwsGenerateStsCredentialsWithParametersResponse interface.
 */
export function instanceOfAwsGenerateStsCredentialsWithParametersResponse(value: object): value is AwsGenerateStsCredentialsWithParametersResponse {
    return true;
}

export function AwsGenerateStsCredentialsWithParametersResponseFromJSON(json: any): AwsGenerateStsCredentialsWithParametersResponse {
    return AwsGenerateStsCredentialsWithParametersResponseFromJSONTyped(json, false);
}

export function AwsGenerateStsCredentialsWithParametersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsGenerateStsCredentialsWithParametersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access_key': json['access_key'] == null ? undefined : json['access_key'],
        'arn': json['arn'] == null ? undefined : json['arn'],
        'secret_key': json['secret_key'] == null ? undefined : json['secret_key'],
        'security_token': json['security_token'] == null ? undefined : json['security_token'],
        'session_token': json['session_token'] == null ? undefined : json['session_token'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
    };
}

export function AwsGenerateStsCredentialsWithParametersResponseToJSON(json: any): AwsGenerateStsCredentialsWithParametersResponse {
    return AwsGenerateStsCredentialsWithParametersResponseToJSONTyped(json, false);
}

export function AwsGenerateStsCredentialsWithParametersResponseToJSONTyped(value?: AwsGenerateStsCredentialsWithParametersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key': value['access_key'],
        'arn': value['arn'],
        'secret_key': value['secret_key'],
        'security_token': value['security_token'],
        'session_token': value['session_token'],
        'ttl': value['ttl'],
    };
}

