/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwsReadIdentityWhitelistTidySettingsResponse
 */
export interface AwsReadIdentityWhitelistTidySettingsResponse {
    /**
     * Whether periodic tidying of identity access-list entries is disabled.
     * @type {boolean}
     * @memberof AwsReadIdentityWhitelistTidySettingsResponse
     */
    disable_periodic_tidy?: boolean;
    /**
     * Duration past expiration before identities are removed from storage.
     * @type {string}
     * @memberof AwsReadIdentityWhitelistTidySettingsResponse
     */
    safety_buffer?: string;
}

/**
 * Check if a given object implements the AwsReadIdentityWhitelistTidySettingsResponse interface.
 */
export function instanceOfAwsReadIdentityWhitelistTidySettingsResponse(value: object): value is AwsReadIdentityWhitelistTidySettingsResponse {
    return true;
}

export function AwsReadIdentityWhitelistTidySettingsResponseFromJSON(json: any): AwsReadIdentityWhitelistTidySettingsResponse {
    return AwsReadIdentityWhitelistTidySettingsResponseFromJSONTyped(json, false);
}

export function AwsReadIdentityWhitelistTidySettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsReadIdentityWhitelistTidySettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'disable_periodic_tidy': json['disable_periodic_tidy'] == null ? undefined : json['disable_periodic_tidy'],
        'safety_buffer': json['safety_buffer'] == null ? undefined : json['safety_buffer'],
    };
}

export function AwsReadIdentityWhitelistTidySettingsResponseToJSON(json: any): AwsReadIdentityWhitelistTidySettingsResponse {
    return AwsReadIdentityWhitelistTidySettingsResponseToJSONTyped(json, false);
}

export function AwsReadIdentityWhitelistTidySettingsResponseToJSONTyped(value?: AwsReadIdentityWhitelistTidySettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disable_periodic_tidy': value['disable_periodic_tidy'],
        'safety_buffer': value['safety_buffer'],
    };
}

