/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwsReadAuthRoleResponse
 */
export interface AwsReadAuthRoleResponse {
    /**
     * Whether instance migration is allowed.
     * @type {boolean}
     * @memberof AwsReadAuthRoleResponse
     */
    allow_instance_migration?: boolean;
    /**
     * Auth type permitted to authenticate to this role.
     * @type {string}
     * @memberof AwsReadAuthRoleResponse
     */
    auth_type?: string;
    /**
     * AWS account IDs that instances must belong to.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_account_id?: Array<object>;
    /**
     * AMI IDs that instances must use to authenticate.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_ami_id?: Array<object>;
    /**
     * EC2 instance IDs that are allowed to authenticate.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_ec2_instance_id?: Array<object>;
    /**
     * IAM instance profile ARN prefixes that instances must match.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_iam_instance_profile_arn?: Array<object>;
    /**
     * IAM principal ARNs bound to this role.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_iam_principal_arn?: Array<object>;
    /**
     * Resolved unique IDs for IAM principal ARNs.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_iam_principal_id?: Array<object>;
    /**
     * IAM role ARNs that instances must match.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_iam_role_arn?: Array<object>;
    /**
     * AWS regions that instances must be in.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_region?: Array<object>;
    /**
     * VPC subnet IDs that instances must be in.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_subnet_id?: Array<object>;
    /**
     * VPC IDs that instances must be in.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    bound_vpc_id?: Array<object>;
    /**
     * Whether reauthentication is disallowed.
     * @type {boolean}
     * @memberof AwsReadAuthRoleResponse
     */
    disallow_reauthentication?: boolean;
    /**
     * AWS region used when inferring the entity type.
     * @type {string}
     * @memberof AwsReadAuthRoleResponse
     */
    inferred_aws_region?: string;
    /**
     * Entity type inferred from the authenticated principal.
     * @type {string}
     * @memberof AwsReadAuthRoleResponse
     */
    inferred_entity_type?: string;
    /**
     * Whether IAM ARNs are resolved to unique IDs.
     * @type {boolean}
     * @memberof AwsReadAuthRoleResponse
     */
    resolve_aws_unique_ids?: boolean;
    /**
     * Unique ID of the role.
     * @type {string}
     * @memberof AwsReadAuthRoleResponse
     */
    role_id?: string;
    /**
     * EC2 instance tag key for role tags.
     * @type {string}
     * @memberof AwsReadAuthRoleResponse
     */
    role_tag?: string;
    /**
     * CIDR blocks that tokens are restricted to.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    token_bound_cidrs?: Array<object>;
    /**
     * Explicit maximum TTL for tokens.
     * @type {number}
     * @memberof AwsReadAuthRoleResponse
     */
    token_explicit_max_ttl?: number;
    /**
     * Maximum TTL for tokens.
     * @type {number}
     * @memberof AwsReadAuthRoleResponse
     */
    token_max_ttl?: number;
    /**
     * Whether the default policy is not added to tokens.
     * @type {boolean}
     * @memberof AwsReadAuthRoleResponse
     */
    token_no_default_policy?: boolean;
    /**
     * Maximum number of token uses.
     * @type {number}
     * @memberof AwsReadAuthRoleResponse
     */
    token_num_uses?: number;
    /**
     * Renewal period for tokens.
     * @type {number}
     * @memberof AwsReadAuthRoleResponse
     */
    token_period?: number;
    /**
     * Policies applied to tokens.
     * @type {Array<object>}
     * @memberof AwsReadAuthRoleResponse
     */
    token_policies?: Array<object>;
    /**
     * TTL for tokens.
     * @type {number}
     * @memberof AwsReadAuthRoleResponse
     */
    token_ttl?: number;
    /**
     * Type of tokens generated.
     * @type {string}
     * @memberof AwsReadAuthRoleResponse
     */
    token_type?: string;
}

/**
 * Check if a given object implements the AwsReadAuthRoleResponse interface.
 */
export function instanceOfAwsReadAuthRoleResponse(value: object): value is AwsReadAuthRoleResponse {
    return true;
}

export function AwsReadAuthRoleResponseFromJSON(json: any): AwsReadAuthRoleResponse {
    return AwsReadAuthRoleResponseFromJSONTyped(json, false);
}

export function AwsReadAuthRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsReadAuthRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allow_instance_migration': json['allow_instance_migration'] == null ? undefined : json['allow_instance_migration'],
        'auth_type': json['auth_type'] == null ? undefined : json['auth_type'],
        'bound_account_id': json['bound_account_id'] == null ? undefined : json['bound_account_id'],
        'bound_ami_id': json['bound_ami_id'] == null ? undefined : json['bound_ami_id'],
        'bound_ec2_instance_id': json['bound_ec2_instance_id'] == null ? undefined : json['bound_ec2_instance_id'],
        'bound_iam_instance_profile_arn': json['bound_iam_instance_profile_arn'] == null ? undefined : json['bound_iam_instance_profile_arn'],
        'bound_iam_principal_arn': json['bound_iam_principal_arn'] == null ? undefined : json['bound_iam_principal_arn'],
        'bound_iam_principal_id': json['bound_iam_principal_id'] == null ? undefined : json['bound_iam_principal_id'],
        'bound_iam_role_arn': json['bound_iam_role_arn'] == null ? undefined : json['bound_iam_role_arn'],
        'bound_region': json['bound_region'] == null ? undefined : json['bound_region'],
        'bound_subnet_id': json['bound_subnet_id'] == null ? undefined : json['bound_subnet_id'],
        'bound_vpc_id': json['bound_vpc_id'] == null ? undefined : json['bound_vpc_id'],
        'disallow_reauthentication': json['disallow_reauthentication'] == null ? undefined : json['disallow_reauthentication'],
        'inferred_aws_region': json['inferred_aws_region'] == null ? undefined : json['inferred_aws_region'],
        'inferred_entity_type': json['inferred_entity_type'] == null ? undefined : json['inferred_entity_type'],
        'resolve_aws_unique_ids': json['resolve_aws_unique_ids'] == null ? undefined : json['resolve_aws_unique_ids'],
        'role_id': json['role_id'] == null ? undefined : json['role_id'],
        'role_tag': json['role_tag'] == null ? undefined : json['role_tag'],
        'token_bound_cidrs': json['token_bound_cidrs'] == null ? undefined : json['token_bound_cidrs'],
        'token_explicit_max_ttl': json['token_explicit_max_ttl'] == null ? undefined : json['token_explicit_max_ttl'],
        'token_max_ttl': json['token_max_ttl'] == null ? undefined : json['token_max_ttl'],
        'token_no_default_policy': json['token_no_default_policy'] == null ? undefined : json['token_no_default_policy'],
        'token_num_uses': json['token_num_uses'] == null ? undefined : json['token_num_uses'],
        'token_period': json['token_period'] == null ? undefined : json['token_period'],
        'token_policies': json['token_policies'] == null ? undefined : json['token_policies'],
        'token_ttl': json['token_ttl'] == null ? undefined : json['token_ttl'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
    };
}

export function AwsReadAuthRoleResponseToJSON(json: any): AwsReadAuthRoleResponse {
    return AwsReadAuthRoleResponseToJSONTyped(json, false);
}

export function AwsReadAuthRoleResponseToJSONTyped(value?: AwsReadAuthRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_instance_migration': value['allow_instance_migration'],
        'auth_type': value['auth_type'],
        'bound_account_id': value['bound_account_id'],
        'bound_ami_id': value['bound_ami_id'],
        'bound_ec2_instance_id': value['bound_ec2_instance_id'],
        'bound_iam_instance_profile_arn': value['bound_iam_instance_profile_arn'],
        'bound_iam_principal_arn': value['bound_iam_principal_arn'],
        'bound_iam_principal_id': value['bound_iam_principal_id'],
        'bound_iam_role_arn': value['bound_iam_role_arn'],
        'bound_region': value['bound_region'],
        'bound_subnet_id': value['bound_subnet_id'],
        'bound_vpc_id': value['bound_vpc_id'],
        'disallow_reauthentication': value['disallow_reauthentication'],
        'inferred_aws_region': value['inferred_aws_region'],
        'inferred_entity_type': value['inferred_entity_type'],
        'resolve_aws_unique_ids': value['resolve_aws_unique_ids'],
        'role_id': value['role_id'],
        'role_tag': value['role_tag'],
        'token_bound_cidrs': value['token_bound_cidrs'],
        'token_explicit_max_ttl': value['token_explicit_max_ttl'],
        'token_max_ttl': value['token_max_ttl'],
        'token_no_default_policy': value['token_no_default_policy'],
        'token_num_uses': value['token_num_uses'],
        'token_period': value['token_period'],
        'token_policies': value['token_policies'],
        'token_ttl': value['token_ttl'],
        'token_type': value['token_type'],
    };
}

