/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwsRotateRootCredentialsResponse
 */
export interface AwsRotateRootCredentialsResponse {
    /**
     * New access key ID of the rotated root IAM credential.
     * @type {string}
     * @memberof AwsRotateRootCredentialsResponse
     */
    access_key?: string;
}

/**
 * Check if a given object implements the AwsRotateRootCredentialsResponse interface.
 */
export function instanceOfAwsRotateRootCredentialsResponse(value: object): value is AwsRotateRootCredentialsResponse {
    return true;
}

export function AwsRotateRootCredentialsResponseFromJSON(json: any): AwsRotateRootCredentialsResponse {
    return AwsRotateRootCredentialsResponseFromJSONTyped(json, false);
}

export function AwsRotateRootCredentialsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsRotateRootCredentialsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access_key': json['access_key'] == null ? undefined : json['access_key'],
    };
}

export function AwsRotateRootCredentialsResponseToJSON(json: any): AwsRotateRootCredentialsResponse {
    return AwsRotateRootCredentialsResponseToJSONTyped(json, false);
}

export function AwsRotateRootCredentialsResponseToJSONTyped(value?: AwsRotateRootCredentialsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key': value['access_key'],
    };
}

