/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwsWriteRoleRequest
 */
export interface AwsWriteRoleRequest {
    /**
     * Use role_arns or policy_arns instead.
     * @type {string}
     * @memberof AwsWriteRoleRequest
     * @deprecated
     */
    arn?: string;
    /**
     * Type of credential to retrieve. Must be one of assumed_role, iam_user, federation_token, or session_token
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    credential_type?: string;
    /**
     * Default TTL for assumed_role, federation_token, and session_token credential types when no TTL is explicitly requested with the credentials
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    default_sts_ttl?: string;
    /**
     * External ID to set when assuming the role; only valid when credential_type is assumed_role
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    external_id?: string;
    /**
     * Names of IAM groups that generated IAM users will be added to. For a credential type of assumed_role or federation_token, the policies sent to the corresponding AWS call (sts:AssumeRole or sts:GetFederation) will be the policies from each group in iam_groups combined with the policy_document and policy_arns parameters.
     * @type {Array<string>}
     * @memberof AwsWriteRoleRequest
     */
    iam_groups?: Array<string>;
    /**
     * IAM tags to be set for any users created by this role. These must be presented as Key-Value pairs. This can be represented as a map or a list of equal sign delimited key pairs.
     * @type {object}
     * @memberof AwsWriteRoleRequest
     */
    iam_tags?: object;
    /**
     * Max allowed TTL for assumed_role, federation_token, and session_token credential types
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    max_sts_ttl?: string;
    /**
     * Identification number or ARN of the MFA device associated with the root config user. Only valid when credential_type is session_token. This is only required when the IAM user has an MFA device configured.
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    mfa_serial_number?: string;
    /**
     * ARN of an IAM policy to attach as a permissions boundary on IAM user credentials; only valid when credential_type isiam_user
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    permissions_boundary_arn?: string;
    /**
     * Use policy_document instead.
     * @type {string}
     * @memberof AwsWriteRoleRequest
     * @deprecated
     */
    policy?: string;
    /**
     * ARNs of AWS policies. Behavior varies by credential_type. When credential_type is iam_user, then it will attach the specified policies to the generated IAM user. When credential_type is assumed_role or federation_token, the policies will be passed as the PolicyArns parameter, acting as a filter on permissions available.
     * @type {Array<string>}
     * @memberof AwsWriteRoleRequest
     */
    policy_arns?: Array<string>;
    /**
     * JSON-encoded IAM policy document. Behavior varies by credential_type. When credential_type is iam_user, then it will attach the contents of the policy_document to the IAM user generated. When credential_type is assumed_role or federation_token, this will be passed in as the Policy parameter to the AssumeRole or GetFederationToken API call, acting as a filter on permissions available.
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    policy_document?: string;
    /**
     * ARNs of AWS roles allowed to be assumed. Only valid when credential_type is assumed_role
     * @type {Array<string>}
     * @memberof AwsWriteRoleRequest
     */
    role_arns?: Array<string>;
    /**
     * Session tags to be set for "assumed_role" creds created by this role. These must be presented as Key-Value pairs. This can be represented as a map or a list of equal sign delimited key pairs.
     * @type {object}
     * @memberof AwsWriteRoleRequest
     */
    session_tags?: object;
    /**
     * Path for IAM User. Only valid when credential_type is iam_user
     * @type {string}
     * @memberof AwsWriteRoleRequest
     */
    user_path?: string;
}

/**
 * Check if a given object implements the AwsWriteRoleRequest interface.
 */
export function instanceOfAwsWriteRoleRequest(value: object): value is AwsWriteRoleRequest {
    return true;
}

export function AwsWriteRoleRequestFromJSON(json: any): AwsWriteRoleRequest {
    return AwsWriteRoleRequestFromJSONTyped(json, false);
}

export function AwsWriteRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsWriteRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'arn': json['arn'] == null ? undefined : json['arn'],
        'credential_type': json['credential_type'] == null ? undefined : json['credential_type'],
        'default_sts_ttl': json['default_sts_ttl'] == null ? undefined : json['default_sts_ttl'],
        'external_id': json['external_id'] == null ? undefined : json['external_id'],
        'iam_groups': json['iam_groups'] == null ? undefined : json['iam_groups'],
        'iam_tags': json['iam_tags'] == null ? undefined : json['iam_tags'],
        'max_sts_ttl': json['max_sts_ttl'] == null ? undefined : json['max_sts_ttl'],
        'mfa_serial_number': json['mfa_serial_number'] == null ? undefined : json['mfa_serial_number'],
        'permissions_boundary_arn': json['permissions_boundary_arn'] == null ? undefined : json['permissions_boundary_arn'],
        'policy': json['policy'] == null ? undefined : json['policy'],
        'policy_arns': json['policy_arns'] == null ? undefined : json['policy_arns'],
        'policy_document': json['policy_document'] == null ? undefined : json['policy_document'],
        'role_arns': json['role_arns'] == null ? undefined : json['role_arns'],
        'session_tags': json['session_tags'] == null ? undefined : json['session_tags'],
        'user_path': json['user_path'] == null ? undefined : json['user_path'],
    };
}

export function AwsWriteRoleRequestToJSON(json: any): AwsWriteRoleRequest {
    return AwsWriteRoleRequestToJSONTyped(json, false);
}

export function AwsWriteRoleRequestToJSONTyped(value?: AwsWriteRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arn': value['arn'],
        'credential_type': value['credential_type'],
        'default_sts_ttl': value['default_sts_ttl'],
        'external_id': value['external_id'],
        'iam_groups': value['iam_groups'],
        'iam_tags': value['iam_tags'],
        'max_sts_ttl': value['max_sts_ttl'],
        'mfa_serial_number': value['mfa_serial_number'],
        'permissions_boundary_arn': value['permissions_boundary_arn'],
        'policy': value['policy'],
        'policy_arns': value['policy_arns'],
        'policy_document': value['policy_document'],
        'role_arns': value['role_arns'],
        'session_tags': value['session_tags'],
        'user_path': value['user_path'],
    };
}

