/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwsWriteAuthRoleRequest
 */
export interface AwsWriteAuthRoleRequest {
    /**
     * The metadata to be tied to generated entity alias. This should be a list or map containing the metadata in key value pairs
     * @type {object}
     * @memberof AwsWriteAuthRoleRequest
     */
    alias_metadata?: object;
    /**
     * If set, allows migration of the underlying instance where the client resides. This keys off of pendingTime in the metadata document, so essentially, this disables the client nonce check whenever the instance is migrated to a new host and pendingTime is newer than the previously-remembered time. Use with caution. This is only checked when auth_type is ec2.
     * @type {boolean}
     * @memberof AwsWriteAuthRoleRequest
     */
    allow_instance_migration?: boolean;
    /**
     * The auth_type permitted to authenticate to this role. Must be one of iam or ec2 and cannot be changed after role creation.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    auth_type?: string;
    /**
     * If set, defines a constraint on the EC2 instances that the account ID in its identity document to match one of the IDs specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_account_id?: Array<string>;
    /**
     * If set, defines a constraint on the EC2 instances that they should be using one of the AMI IDs specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_ami_id?: Array<string>;
    /**
     * If set, defines a constraint on the EC2 instances to have one of the given instance IDs. Can be a list or comma-separated string of EC2 instance IDs. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_ec2_instance_id?: Array<string>;
    /**
     * If set, defines a constraint on the EC2 instances to be associated with an IAM instance profile ARN which has a prefix that matches one of the values specified by this parameter. The value is prefix-matched (as though it were a glob ending in '*'). This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_iam_instance_profile_arn?: Array<string>;
    /**
     * ARN of the IAM principals to bind to this role. Only applicable when auth_type is iam.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_iam_principal_arn?: Array<string>;
    /**
     * If set, defines a constraint on the authenticating EC2 instance that it must match one of the IAM role ARNs specified by this parameter. The value is prefix-matched (as though it were a glob ending in '*'). The configured IAM user or EC2 instance role must be allowed to execute the 'iam:GetInstanceProfile' action if this is specified. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_iam_role_arn?: Array<string>;
    /**
     * If set, defines a constraint on the EC2 instances that the region in its identity document match one of the regions specified by this parameter. This is only applicable when auth_type is ec2.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_region?: Array<string>;
    /**
     * If set, defines a constraint on the EC2 instance to be associated with the subnet ID that matches one of the values specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_subnet_id?: Array<string>;
    /**
     * If set, defines a constraint on the EC2 instance to be associated with a VPC ID that matches one of the value specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    bound_vpc_id?: Array<string>;
    /**
     * If set, only allows a single token to be granted per instance ID. In order to perform a fresh login, the entry in the access list for the instance ID needs to be cleared using 'auth/aws-ec2/identity-accesslist/<instance_id>' endpoint. This is only applicable when auth_type is ec2.
     * @type {boolean}
     * @memberof AwsWriteAuthRoleRequest
     */
    disallow_reauthentication?: boolean;
    /**
     * When auth_type is iam and inferred_entity_type is set, the region to assume the inferred entity exists in.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    inferred_aws_region?: string;
    /**
     * When auth_type is iam, the AWS entity type to infer from the authenticated principal. The only supported value is ec2_instance, which will extract the EC2 instance ID from the authenticated role and apply the following restrictions specific to EC2 instances: bound_ami_id, bound_account_id, bound_iam_role_arn, bound_iam_instance_profile_arn, bound_vpc_id, bound_subnet_id. The configured EC2 client must be able to find the inferred instance ID in the results, and the instance must be running. If unable to determine the EC2 instance ID or unable to find the EC2 instance ID among running instances, then authentication will fail.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    inferred_entity_type?: string;
    /**
     * Use "token_max_ttl" instead. If this and "token_max_ttl" are both specified, only "token_max_ttl" will be used.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     * @deprecated
     */
    max_ttl?: string;
    /**
     * Use "token_period" instead. If this and "token_period" are both specified, only "token_period" will be used.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     * @deprecated
     */
    period?: string;
    /**
     * Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     * @deprecated
     */
    policies?: Array<string>;
    /**
     * If set, resolve all AWS IAM ARNs into AWS's internal unique IDs. When an IAM entity (e.g., user, role, or instance profile) is deleted, then all references to it within the role will be invalidated, which prevents a new IAM entity from being created with the same name and matching the role's IAM binds. Once set, this cannot be unset.
     * @type {boolean}
     * @memberof AwsWriteAuthRoleRequest
     */
    resolve_aws_unique_ids?: boolean;
    /**
     * If set, enables the role tags for this role. The value set for this field should be the 'key' of the tag on the EC2 instance. The 'value' of the tag should be generated using 'role/<role>/tag' endpoint. Defaults to an empty string, meaning that role tags are disabled. This is only allowed if auth_type is ec2.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    role_tag?: string;
    /**
     * Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_bound_cidrs?: Array<string>;
    /**
     * If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_explicit_max_ttl?: string;
    /**
     * The maximum lifetime of the generated token
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_max_ttl?: string;
    /**
     * If true, the 'default' policy will not automatically be added to generated tokens
     * @type {boolean}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_no_default_policy?: boolean;
    /**
     * The maximum number of times a token may be used, a value of zero means unlimited
     * @type {number}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_num_uses?: number;
    /**
     * If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_period?: string;
    /**
     * Comma-separated list of policies
     * @type {Array<string>}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_policies?: Array<string>;
    /**
     * The initial ttl of the token to generate
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_ttl?: string;
    /**
     * The type of token to generate, service or batch
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     */
    token_type?: string;
    /**
     * Use "token_ttl" instead. If this and "token_ttl" are both specified, only "token_ttl" will be used.
     * @type {string}
     * @memberof AwsWriteAuthRoleRequest
     * @deprecated
     */
    ttl?: string;
}

/**
 * Check if a given object implements the AwsWriteAuthRoleRequest interface.
 */
export function instanceOfAwsWriteAuthRoleRequest(value: object): value is AwsWriteAuthRoleRequest {
    return true;
}

export function AwsWriteAuthRoleRequestFromJSON(json: any): AwsWriteAuthRoleRequest {
    return AwsWriteAuthRoleRequestFromJSONTyped(json, false);
}

export function AwsWriteAuthRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsWriteAuthRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alias_metadata': json['alias_metadata'] == null ? undefined : json['alias_metadata'],
        'allow_instance_migration': json['allow_instance_migration'] == null ? undefined : json['allow_instance_migration'],
        'auth_type': json['auth_type'] == null ? undefined : json['auth_type'],
        'bound_account_id': json['bound_account_id'] == null ? undefined : json['bound_account_id'],
        'bound_ami_id': json['bound_ami_id'] == null ? undefined : json['bound_ami_id'],
        'bound_ec2_instance_id': json['bound_ec2_instance_id'] == null ? undefined : json['bound_ec2_instance_id'],
        'bound_iam_instance_profile_arn': json['bound_iam_instance_profile_arn'] == null ? undefined : json['bound_iam_instance_profile_arn'],
        'bound_iam_principal_arn': json['bound_iam_principal_arn'] == null ? undefined : json['bound_iam_principal_arn'],
        'bound_iam_role_arn': json['bound_iam_role_arn'] == null ? undefined : json['bound_iam_role_arn'],
        'bound_region': json['bound_region'] == null ? undefined : json['bound_region'],
        'bound_subnet_id': json['bound_subnet_id'] == null ? undefined : json['bound_subnet_id'],
        'bound_vpc_id': json['bound_vpc_id'] == null ? undefined : json['bound_vpc_id'],
        'disallow_reauthentication': json['disallow_reauthentication'] == null ? undefined : json['disallow_reauthentication'],
        'inferred_aws_region': json['inferred_aws_region'] == null ? undefined : json['inferred_aws_region'],
        'inferred_entity_type': json['inferred_entity_type'] == null ? undefined : json['inferred_entity_type'],
        'max_ttl': json['max_ttl'] == null ? undefined : json['max_ttl'],
        'period': json['period'] == null ? undefined : json['period'],
        'policies': json['policies'] == null ? undefined : json['policies'],
        'resolve_aws_unique_ids': json['resolve_aws_unique_ids'] == null ? undefined : json['resolve_aws_unique_ids'],
        'role_tag': json['role_tag'] == null ? undefined : json['role_tag'],
        'token_bound_cidrs': json['token_bound_cidrs'] == null ? undefined : json['token_bound_cidrs'],
        'token_explicit_max_ttl': json['token_explicit_max_ttl'] == null ? undefined : json['token_explicit_max_ttl'],
        'token_max_ttl': json['token_max_ttl'] == null ? undefined : json['token_max_ttl'],
        'token_no_default_policy': json['token_no_default_policy'] == null ? undefined : json['token_no_default_policy'],
        'token_num_uses': json['token_num_uses'] == null ? undefined : json['token_num_uses'],
        'token_period': json['token_period'] == null ? undefined : json['token_period'],
        'token_policies': json['token_policies'] == null ? undefined : json['token_policies'],
        'token_ttl': json['token_ttl'] == null ? undefined : json['token_ttl'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
    };
}

export function AwsWriteAuthRoleRequestToJSON(json: any): AwsWriteAuthRoleRequest {
    return AwsWriteAuthRoleRequestToJSONTyped(json, false);
}

export function AwsWriteAuthRoleRequestToJSONTyped(value?: AwsWriteAuthRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias_metadata': value['alias_metadata'],
        'allow_instance_migration': value['allow_instance_migration'],
        'auth_type': value['auth_type'],
        'bound_account_id': value['bound_account_id'],
        'bound_ami_id': value['bound_ami_id'],
        'bound_ec2_instance_id': value['bound_ec2_instance_id'],
        'bound_iam_instance_profile_arn': value['bound_iam_instance_profile_arn'],
        'bound_iam_principal_arn': value['bound_iam_principal_arn'],
        'bound_iam_role_arn': value['bound_iam_role_arn'],
        'bound_region': value['bound_region'],
        'bound_subnet_id': value['bound_subnet_id'],
        'bound_vpc_id': value['bound_vpc_id'],
        'disallow_reauthentication': value['disallow_reauthentication'],
        'inferred_aws_region': value['inferred_aws_region'],
        'inferred_entity_type': value['inferred_entity_type'],
        'max_ttl': value['max_ttl'],
        'period': value['period'],
        'policies': value['policies'],
        'resolve_aws_unique_ids': value['resolve_aws_unique_ids'],
        'role_tag': value['role_tag'],
        'token_bound_cidrs': value['token_bound_cidrs'],
        'token_explicit_max_ttl': value['token_explicit_max_ttl'],
        'token_max_ttl': value['token_max_ttl'],
        'token_no_default_policy': value['token_no_default_policy'],
        'token_num_uses': value['token_num_uses'],
        'token_period': value['token_period'],
        'token_policies': value['token_policies'],
        'token_ttl': value['token_ttl'],
        'token_type': value['token_type'],
        'ttl': value['ttl'],
    };
}

