/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AzureReadAuthConfigurationResponse
 */
export interface AzureReadAuthConfigurationResponse {
    /**
     * The authentication type used to connect to Azure.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    auth_type?: string;
    /**
     * The OAuth2 client id to connection to Azure.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    client_id?: string;
    /**
     * Whether automated rotation is disabled.
     * @type {boolean}
     * @memberof AzureReadAuthConfigurationResponse
     */
    disable_automated_rotation?: boolean;
    /**
     * The Azure environment name.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    environment?: string;
    /**
     * Audience of plugin identity tokens.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    identity_token_audience?: string;
    /**
     * Time-to-live of plugin identity tokens.
     * @type {number}
     * @memberof AzureReadAuthConfigurationResponse
     */
    identity_token_ttl?: number;
    /**
     * The maximum number of attempts a failed operation will be retried.
     * @type {number}
     * @memberof AzureReadAuthConfigurationResponse
     */
    max_retries?: number;
    /**
     * The maximum delay allowed before retrying an operation.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    max_retry_delay?: string;
    /**
     * The resource URL for the vault application in Azure Active Directory.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    resource?: string;
    /**
     * The initial amount of delay to use before retrying an operation.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    retry_delay?: string;
    /**
     * The expiration date of the root password.
     * @type {Date}
     * @memberof AzureReadAuthConfigurationResponse
     */
    root_password_expiration_date?: Date;
    /**
     * The TTL of the root password in Azure.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    root_password_ttl?: string;
    /**
     * The period for automated root credential rotation.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    rotation_period?: string;
    /**
     * The rotation policy name.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    rotation_policy?: string;
    /**
     * The schedule for automated root credential rotation.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    rotation_schedule?: string;
    /**
     * The maximum time allowed for a rotation to complete.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    rotation_window?: string;
    /**
     * The tenant id for the Azure Active Directory.
     * @type {string}
     * @memberof AzureReadAuthConfigurationResponse
     */
    tenant_id?: string;
}

/**
 * Check if a given object implements the AzureReadAuthConfigurationResponse interface.
 */
export function instanceOfAzureReadAuthConfigurationResponse(value: object): value is AzureReadAuthConfigurationResponse {
    return true;
}

export function AzureReadAuthConfigurationResponseFromJSON(json: any): AzureReadAuthConfigurationResponse {
    return AzureReadAuthConfigurationResponseFromJSONTyped(json, false);
}

export function AzureReadAuthConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureReadAuthConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'auth_type': json['auth_type'] == null ? undefined : json['auth_type'],
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'disable_automated_rotation': json['disable_automated_rotation'] == null ? undefined : json['disable_automated_rotation'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'identity_token_audience': json['identity_token_audience'] == null ? undefined : json['identity_token_audience'],
        'identity_token_ttl': json['identity_token_ttl'] == null ? undefined : json['identity_token_ttl'],
        'max_retries': json['max_retries'] == null ? undefined : json['max_retries'],
        'max_retry_delay': json['max_retry_delay'] == null ? undefined : json['max_retry_delay'],
        'resource': json['resource'] == null ? undefined : json['resource'],
        'retry_delay': json['retry_delay'] == null ? undefined : json['retry_delay'],
        'root_password_expiration_date': json['root_password_expiration_date'] == null ? undefined : (new Date(json['root_password_expiration_date'])),
        'root_password_ttl': json['root_password_ttl'] == null ? undefined : json['root_password_ttl'],
        'rotation_period': json['rotation_period'] == null ? undefined : json['rotation_period'],
        'rotation_policy': json['rotation_policy'] == null ? undefined : json['rotation_policy'],
        'rotation_schedule': json['rotation_schedule'] == null ? undefined : json['rotation_schedule'],
        'rotation_window': json['rotation_window'] == null ? undefined : json['rotation_window'],
        'tenant_id': json['tenant_id'] == null ? undefined : json['tenant_id'],
    };
}

export function AzureReadAuthConfigurationResponseToJSON(json: any): AzureReadAuthConfigurationResponse {
    return AzureReadAuthConfigurationResponseToJSONTyped(json, false);
}

export function AzureReadAuthConfigurationResponseToJSONTyped(value?: AzureReadAuthConfigurationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_type': value['auth_type'],
        'client_id': value['client_id'],
        'disable_automated_rotation': value['disable_automated_rotation'],
        'environment': value['environment'],
        'identity_token_audience': value['identity_token_audience'],
        'identity_token_ttl': value['identity_token_ttl'],
        'max_retries': value['max_retries'],
        'max_retry_delay': value['max_retry_delay'],
        'resource': value['resource'],
        'retry_delay': value['retry_delay'],
        'root_password_expiration_date': value['root_password_expiration_date'] == null ? undefined : ((value['root_password_expiration_date']).toISOString()),
        'root_password_ttl': value['root_password_ttl'],
        'rotation_period': value['rotation_period'],
        'rotation_policy': value['rotation_policy'],
        'rotation_schedule': value['rotation_schedule'],
        'rotation_window': value['rotation_window'],
        'tenant_id': value['tenant_id'],
    };
}

