/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AzureRequestAccessTokenRequest
 */
export interface AzureRequestAccessTokenRequest {
    /**
     * The full Azure scope to request a token for (e.g., https://graph.microsoft.com/.default).
     * @type {string}
     * @memberof AzureRequestAccessTokenRequest
     */
    scope: string;
}

/**
 * Check if a given object implements the AzureRequestAccessTokenRequest interface.
 */
export function instanceOfAzureRequestAccessTokenRequest(value: object): value is AzureRequestAccessTokenRequest {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function AzureRequestAccessTokenRequestFromJSON(json: any): AzureRequestAccessTokenRequest {
    return AzureRequestAccessTokenRequestFromJSONTyped(json, false);
}

export function AzureRequestAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureRequestAccessTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
    };
}

export function AzureRequestAccessTokenRequestToJSON(json: any): AzureRequestAccessTokenRequest {
    return AzureRequestAccessTokenRequestToJSONTyped(json, false);
}

export function AzureRequestAccessTokenRequestToJSONTyped(value?: AzureRequestAccessTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
    };
}

