/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AzureReadAuthRoleResponse
 */
export interface AzureReadAuthRoleResponse {
    /**
     * List of group ids that login is restricted to.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    bound_group_ids?: Array<string>;
    /**
     * List of locations that login is restricted to.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    bound_locations?: Array<string>;
    /**
     * List of resource groups that login is restricted to.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    bound_resource_groups?: Array<string>;
    /**
     * List of scale sets that login is restricted to.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    bound_scale_sets?: Array<string>;
    /**
     * List of service principal ids that login is restricted to.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    bound_service_principal_ids?: Array<string>;
    /**
     * List of subscription ids that login is restricted to.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    bound_subscription_ids?: Array<string>;
    /**
     * Use "token_max_ttl" instead. If this and "token_max_ttl" are both specified, only "token_max_ttl" will be used.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     * @deprecated
     */
    max_ttl?: number;
    /**
     * Use "token_num_uses" instead. If this and "token_num_uses" are both specified, only "token_num_uses" will be used.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     * @deprecated
     */
    num_uses?: number;
    /**
     * Use "token_period" instead. If this and "token_period" are both specified, only "token_period" will be used.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     * @deprecated
     */
    period?: number;
    /**
     * Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     * @deprecated
     */
    policies?: Array<string>;
    /**
     * List of CIDR blocks that tokens are restricted to.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    token_bound_cidrs?: Array<string>;
    /**
     * The maximum TTL for tokens, overriding the system maximum.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     */
    token_explicit_max_ttl?: number;
    /**
     * The maximum lifetime of the token.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     */
    token_max_ttl?: number;
    /**
     * If true, the default policy will not be added to tokens.
     * @type {boolean}
     * @memberof AzureReadAuthRoleResponse
     */
    token_no_default_policy?: boolean;
    /**
     * The maximum number of uses for the token.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     */
    token_num_uses?: number;
    /**
     * The period for periodic tokens.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     */
    token_period?: number;
    /**
     * List of policies on the token.
     * @type {Array<string>}
     * @memberof AzureReadAuthRoleResponse
     */
    token_policies?: Array<string>;
    /**
     * The incremental lifetime for generated tokens.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     */
    token_ttl?: number;
    /**
     * The token type.
     * @type {string}
     * @memberof AzureReadAuthRoleResponse
     */
    token_type?: string;
    /**
     * Use "token_ttl" instead. If this and "token_ttl" are both specified, only "token_ttl" will be used.
     * @type {number}
     * @memberof AzureReadAuthRoleResponse
     * @deprecated
     */
    ttl?: number;
}

/**
 * Check if a given object implements the AzureReadAuthRoleResponse interface.
 */
export function instanceOfAzureReadAuthRoleResponse(value: object): value is AzureReadAuthRoleResponse {
    return true;
}

export function AzureReadAuthRoleResponseFromJSON(json: any): AzureReadAuthRoleResponse {
    return AzureReadAuthRoleResponseFromJSONTyped(json, false);
}

export function AzureReadAuthRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureReadAuthRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bound_group_ids': json['bound_group_ids'] == null ? undefined : json['bound_group_ids'],
        'bound_locations': json['bound_locations'] == null ? undefined : json['bound_locations'],
        'bound_resource_groups': json['bound_resource_groups'] == null ? undefined : json['bound_resource_groups'],
        'bound_scale_sets': json['bound_scale_sets'] == null ? undefined : json['bound_scale_sets'],
        'bound_service_principal_ids': json['bound_service_principal_ids'] == null ? undefined : json['bound_service_principal_ids'],
        'bound_subscription_ids': json['bound_subscription_ids'] == null ? undefined : json['bound_subscription_ids'],
        'max_ttl': json['max_ttl'] == null ? undefined : json['max_ttl'],
        'num_uses': json['num_uses'] == null ? undefined : json['num_uses'],
        'period': json['period'] == null ? undefined : json['period'],
        'policies': json['policies'] == null ? undefined : json['policies'],
        'token_bound_cidrs': json['token_bound_cidrs'] == null ? undefined : json['token_bound_cidrs'],
        'token_explicit_max_ttl': json['token_explicit_max_ttl'] == null ? undefined : json['token_explicit_max_ttl'],
        'token_max_ttl': json['token_max_ttl'] == null ? undefined : json['token_max_ttl'],
        'token_no_default_policy': json['token_no_default_policy'] == null ? undefined : json['token_no_default_policy'],
        'token_num_uses': json['token_num_uses'] == null ? undefined : json['token_num_uses'],
        'token_period': json['token_period'] == null ? undefined : json['token_period'],
        'token_policies': json['token_policies'] == null ? undefined : json['token_policies'],
        'token_ttl': json['token_ttl'] == null ? undefined : json['token_ttl'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
    };
}

export function AzureReadAuthRoleResponseToJSON(json: any): AzureReadAuthRoleResponse {
    return AzureReadAuthRoleResponseToJSONTyped(json, false);
}

export function AzureReadAuthRoleResponseToJSONTyped(value?: AzureReadAuthRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bound_group_ids': value['bound_group_ids'],
        'bound_locations': value['bound_locations'],
        'bound_resource_groups': value['bound_resource_groups'],
        'bound_scale_sets': value['bound_scale_sets'],
        'bound_service_principal_ids': value['bound_service_principal_ids'],
        'bound_subscription_ids': value['bound_subscription_ids'],
        'max_ttl': value['max_ttl'],
        'num_uses': value['num_uses'],
        'period': value['period'],
        'policies': value['policies'],
        'token_bound_cidrs': value['token_bound_cidrs'],
        'token_explicit_max_ttl': value['token_explicit_max_ttl'],
        'token_max_ttl': value['token_max_ttl'],
        'token_no_default_policy': value['token_no_default_policy'],
        'token_num_uses': value['token_num_uses'],
        'token_period': value['token_period'],
        'token_policies': value['token_policies'],
        'token_ttl': value['token_ttl'],
        'token_type': value['token_type'],
        'ttl': value['ttl'],
    };
}

