/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudFoundryReadConfigurationResponse
 */
export interface CloudFoundryReadConfigurationResponse {
    /**
     * Address of the CF API.
     * @type {string}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    cf_api_addr?: string;
    /**
     * PEM-format certificate used for mutual TLS with the CF API.
     * @type {string}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    cf_api_mutual_tls_certificate?: string;
    /**
     * PEM-format CA certificates trusted for the CF API.
     * @type {Array<string>}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    cf_api_trusted_certificates?: Array<string>;
    /**
     * Client ID for the CF API.
     * @type {string}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    cf_client_id?: string;
    /**
     * Timeout in seconds for CF API calls.
     * @type {number}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    cf_timeout?: number;
    /**
     * Username for the CF API.
     * @type {string}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    cf_username?: string;
    /**
     * Whether a new CF client is created for every login request.
     * @type {boolean}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    force_new_client?: boolean;
    /**
     * PEM-format CA certificates used to verify instance certificates.
     * @type {Array<string>}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    identity_ca_certificates?: Array<string>;
    /**
     * Maximum acceptable future offset of a signing_time in seconds.
     * @type {number}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    login_max_seconds_not_after?: number;
    /**
     * Maximum acceptable age of a signing_time in seconds.
     * @type {number}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    login_max_seconds_not_before?: number;
    /**
     * Configuration schema version.
     * @type {number}
     * @memberof CloudFoundryReadConfigurationResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the CloudFoundryReadConfigurationResponse interface.
 */
export function instanceOfCloudFoundryReadConfigurationResponse(value: object): value is CloudFoundryReadConfigurationResponse {
    return true;
}

export function CloudFoundryReadConfigurationResponseFromJSON(json: any): CloudFoundryReadConfigurationResponse {
    return CloudFoundryReadConfigurationResponseFromJSONTyped(json, false);
}

export function CloudFoundryReadConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudFoundryReadConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cf_api_addr': json['cf_api_addr'] == null ? undefined : json['cf_api_addr'],
        'cf_api_mutual_tls_certificate': json['cf_api_mutual_tls_certificate'] == null ? undefined : json['cf_api_mutual_tls_certificate'],
        'cf_api_trusted_certificates': json['cf_api_trusted_certificates'] == null ? undefined : json['cf_api_trusted_certificates'],
        'cf_client_id': json['cf_client_id'] == null ? undefined : json['cf_client_id'],
        'cf_timeout': json['cf_timeout'] == null ? undefined : json['cf_timeout'],
        'cf_username': json['cf_username'] == null ? undefined : json['cf_username'],
        'force_new_client': json['force_new_client'] == null ? undefined : json['force_new_client'],
        'identity_ca_certificates': json['identity_ca_certificates'] == null ? undefined : json['identity_ca_certificates'],
        'login_max_seconds_not_after': json['login_max_seconds_not_after'] == null ? undefined : json['login_max_seconds_not_after'],
        'login_max_seconds_not_before': json['login_max_seconds_not_before'] == null ? undefined : json['login_max_seconds_not_before'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function CloudFoundryReadConfigurationResponseToJSON(json: any): CloudFoundryReadConfigurationResponse {
    return CloudFoundryReadConfigurationResponseToJSONTyped(json, false);
}

export function CloudFoundryReadConfigurationResponseToJSONTyped(value?: CloudFoundryReadConfigurationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cf_api_addr': value['cf_api_addr'],
        'cf_api_mutual_tls_certificate': value['cf_api_mutual_tls_certificate'],
        'cf_api_trusted_certificates': value['cf_api_trusted_certificates'],
        'cf_client_id': value['cf_client_id'],
        'cf_timeout': value['cf_timeout'],
        'cf_username': value['cf_username'],
        'force_new_client': value['force_new_client'],
        'identity_ca_certificates': value['identity_ca_certificates'],
        'login_max_seconds_not_after': value['login_max_seconds_not_after'],
        'login_max_seconds_not_before': value['login_max_seconds_not_before'],
        'version': value['version'],
    };
}

