/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorsReadConfigurationResponse
 */
export interface CorsReadConfigurationResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof CorsReadConfigurationResponse
     */
    allowed_headers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CorsReadConfigurationResponse
     */
    allowed_origins?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CorsReadConfigurationResponse
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the CorsReadConfigurationResponse interface.
 */
export function instanceOfCorsReadConfigurationResponse(value: object): value is CorsReadConfigurationResponse {
    return true;
}

export function CorsReadConfigurationResponseFromJSON(json: any): CorsReadConfigurationResponse {
    return CorsReadConfigurationResponseFromJSONTyped(json, false);
}

export function CorsReadConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorsReadConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed_headers': json['allowed_headers'] == null ? undefined : json['allowed_headers'],
        'allowed_origins': json['allowed_origins'] == null ? undefined : json['allowed_origins'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function CorsReadConfigurationResponseToJSON(json: any): CorsReadConfigurationResponse {
    return CorsReadConfigurationResponseToJSONTyped(json, false);
}

export function CorsReadConfigurationResponseToJSONTyped(value?: CorsReadConfigurationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed_headers': value['allowed_headers'],
        'allowed_origins': value['allowed_origins'],
        'enabled': value['enabled'],
    };
}

