/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRequest
 */
export interface CreateRequest {
    /**
     * A comma-separated list of attribute names to include in the response.
     * @type {Array<string>}
     * @memberof CreateRequest
     */
    attributes?: Array<string>;
    /**
     * The desired number of results per page.
     * @type {number}
     * @memberof CreateRequest
     */
    count?: number;
    /**
     * A comma-separated list of attribute names to exclude from the response.
     * @type {Array<string>}
     * @memberof CreateRequest
     */
    excludedAttributes?: Array<string>;
    /**
     * ID of the group. If set, updates the corresponding existing entity.
     * @type {string}
     * @memberof CreateRequest
     */
    id?: string;
    /**
     * The 1-based index of the first result to return.
     * @type {number}
     * @memberof CreateRequest
     */
    startIndex?: number;
}

/**
 * Check if a given object implements the CreateRequest interface.
 */
export function instanceOfCreateRequest(value: object): value is CreateRequest {
    return true;
}

export function CreateRequestFromJSON(json: any): CreateRequest {
    return CreateRequestFromJSONTyped(json, false);
}

export function CreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'count': json['count'] == null ? undefined : json['count'],
        'excludedAttributes': json['excludedAttributes'] == null ? undefined : json['excludedAttributes'],
        'id': json['id'] == null ? undefined : json['id'],
        'startIndex': json['startIndex'] == null ? undefined : json['startIndex'],
    };
}

export function CreateRequestToJSON(json: any): CreateRequest {
    return CreateRequestToJSONTyped(json, false);
}

export function CreateRequestToJSONTyped(value?: CreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'],
        'count': value['count'],
        'excludedAttributes': value['excludedAttributes'],
        'id': value['id'],
        'startIndex': value['startIndex'],
    };
}

