/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatabaseWriteStaticRoleRequest
 */
export interface DatabaseWriteStaticRoleRequest {
    /**
     * The configuration for the given credential_type.
     * @type {object}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    credential_config?: object;
    /**
     * The type of credential to manage. Options include: 'password', 'rsa_private_key'. Defaults to 'password'.
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    credential_type?: string;
    /**
     * Name of the database this role acts on.
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    db_name?: string;
    /**
     * Enterprise only. If set, the initial static account password of the external db user before the first Vault rotatation.
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    password?: string;
    /**
     * Period for automatic credential rotation of the given username. Not valid unless used with "username". Mutually exclusive with "rotation_schedule."
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    rotation_period?: string;
    /**
     * Schedule for automatic credential rotation of the given username. Mutually exclusive with "rotation_period."
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    rotation_schedule?: string;
    /**
     * Specifies the database statements to be executed to rotate the accounts credentials. Not every plugin type will support this functionality. See the plugin's API page for more information on support and formatting for this parameter.
     * @type {Array<string>}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    rotation_statements?: Array<string>;
    /**
     * The window of time in which rotations are allowed to occur starting from a given "rotation_schedule". Requires "rotation_schedule" to be specified
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    rotation_window?: string;
    /**
     * Used to connect to a self-managed static account. Must be provided by the user when root credentials are not provided.
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     * @deprecated
     */
    self_managed_password?: string;
    /**
     * Enterprise only. If true, the static account password will not be rotated on creation of the role. Defaults to false.
     * @type {boolean}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    skip_import_rotation?: boolean;
    /**
     * Name of the static user account for Vault to manage. Requires "rotation_period" to be specified
     * @type {string}
     * @memberof DatabaseWriteStaticRoleRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the DatabaseWriteStaticRoleRequest interface.
 */
export function instanceOfDatabaseWriteStaticRoleRequest(value: object): value is DatabaseWriteStaticRoleRequest {
    return true;
}

export function DatabaseWriteStaticRoleRequestFromJSON(json: any): DatabaseWriteStaticRoleRequest {
    return DatabaseWriteStaticRoleRequestFromJSONTyped(json, false);
}

export function DatabaseWriteStaticRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatabaseWriteStaticRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'credential_config': json['credential_config'] == null ? undefined : json['credential_config'],
        'credential_type': json['credential_type'] == null ? undefined : json['credential_type'],
        'db_name': json['db_name'] == null ? undefined : json['db_name'],
        'password': json['password'] == null ? undefined : json['password'],
        'rotation_period': json['rotation_period'] == null ? undefined : json['rotation_period'],
        'rotation_schedule': json['rotation_schedule'] == null ? undefined : json['rotation_schedule'],
        'rotation_statements': json['rotation_statements'] == null ? undefined : json['rotation_statements'],
        'rotation_window': json['rotation_window'] == null ? undefined : json['rotation_window'],
        'self_managed_password': json['self_managed_password'] == null ? undefined : json['self_managed_password'],
        'skip_import_rotation': json['skip_import_rotation'] == null ? undefined : json['skip_import_rotation'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function DatabaseWriteStaticRoleRequestToJSON(json: any): DatabaseWriteStaticRoleRequest {
    return DatabaseWriteStaticRoleRequestToJSONTyped(json, false);
}

export function DatabaseWriteStaticRoleRequestToJSONTyped(value?: DatabaseWriteStaticRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credential_config': value['credential_config'],
        'credential_type': value['credential_type'],
        'db_name': value['db_name'],
        'password': value['password'],
        'rotation_period': value['rotation_period'],
        'rotation_schedule': value['rotation_schedule'],
        'rotation_statements': value['rotation_statements'],
        'rotation_window': value['rotation_window'],
        'self_managed_password': value['self_managed_password'],
        'skip_import_rotation': value['skip_import_rotation'],
        'username': value['username'],
    };
}

