/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleCloudKmsReadConfigurationResponse
 */
export interface GoogleCloudKmsReadConfigurationResponse {
    /**
     * List of OAuth2 scopes requested when authenticating.
     * @type {Array<string>}
     * @memberof GoogleCloudKmsReadConfigurationResponse
     */
    scopes?: Array<string>;
}

/**
 * Check if a given object implements the GoogleCloudKmsReadConfigurationResponse interface.
 */
export function instanceOfGoogleCloudKmsReadConfigurationResponse(value: object): value is GoogleCloudKmsReadConfigurationResponse {
    return true;
}

export function GoogleCloudKmsReadConfigurationResponseFromJSON(json: any): GoogleCloudKmsReadConfigurationResponse {
    return GoogleCloudKmsReadConfigurationResponseFromJSONTyped(json, false);
}

export function GoogleCloudKmsReadConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleCloudKmsReadConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
    };
}

export function GoogleCloudKmsReadConfigurationResponseToJSON(json: any): GoogleCloudKmsReadConfigurationResponse {
    return GoogleCloudKmsReadConfigurationResponseToJSONTyped(json, false);
}

export function GoogleCloudKmsReadConfigurationResponseToJSONTyped(value?: GoogleCloudKmsReadConfigurationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scopes': value['scopes'],
    };
}

