/**
 * Copyright (c) HashiCorp, Inc.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleCloudWriteStaticAccountRequest
 */
export interface GoogleCloudWriteStaticAccountRequest {
    /**
     * Bindings configuration string.
     * @type {string}
     * @memberof GoogleCloudWriteStaticAccountRequest
     */
    bindings?: string;
    /**
     * Type of secret generated for this account. Cannot be updated. Defaults to "access_token"
     * @type {string}
     * @memberof GoogleCloudWriteStaticAccountRequest
     */
    secret_type?: string;
    /**
     * Required. Email of the GCP service account to manage. Cannot be updated.
     * @type {string}
     * @memberof GoogleCloudWriteStaticAccountRequest
     */
    service_account_email?: string;
    /**
     * List of OAuth scopes to assign to access tokens generated under this account. Ignored if "secret_type" is not ""access_token""
     * @type {Array<string>}
     * @memberof GoogleCloudWriteStaticAccountRequest
     */
    token_scopes?: Array<string>;
}

/**
 * Check if a given object implements the GoogleCloudWriteStaticAccountRequest interface.
 */
export function instanceOfGoogleCloudWriteStaticAccountRequest(value: object): value is GoogleCloudWriteStaticAccountRequest {
    return true;
}

export function GoogleCloudWriteStaticAccountRequestFromJSON(json: any): GoogleCloudWriteStaticAccountRequest {
    return GoogleCloudWriteStaticAccountRequestFromJSONTyped(json, false);
}

export function GoogleCloudWriteStaticAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleCloudWriteStaticAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bindings': json['bindings'] == null ? undefined : json['bindings'],
        'secret_type': json['secret_type'] == null ? undefined : json['secret_type'],
        'service_account_email': json['service_account_email'] == null ? undefined : json['service_account_email'],
        'token_scopes': json['token_scopes'] == null ? undefined : json['token_scopes'],
    };
}

export function GoogleCloudWriteStaticAccountRequestToJSON(json: any): GoogleCloudWriteStaticAccountRequest {
    return GoogleCloudWriteStaticAccountRequestToJSONTyped(json, false);
}

export function GoogleCloudWriteStaticAccountRequestToJSONTyped(value?: GoogleCloudWriteStaticAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bindings': value['bindings'],
        'secret_type': value['secret_type'],
        'service_account_email': value['service_account_email'],
        'token_scopes': value['token_scopes'],
    };
}

