/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleCloudGenerateRolesetKeyResponse
 */
export interface GoogleCloudGenerateRolesetKeyResponse {
    /**
     * Algorithm used to generate the service account key.
     * @type {string}
     * @memberof GoogleCloudGenerateRolesetKeyResponse
     */
    key_algorithm?: string;
    /**
     * Private key type of the service account key.
     * @type {string}
     * @memberof GoogleCloudGenerateRolesetKeyResponse
     */
    key_type?: string;
    /**
     * Base64-encoded private key data for the service account key.
     * @type {string}
     * @memberof GoogleCloudGenerateRolesetKeyResponse
     */
    private_key_data?: string;
}

/**
 * Check if a given object implements the GoogleCloudGenerateRolesetKeyResponse interface.
 */
export function instanceOfGoogleCloudGenerateRolesetKeyResponse(value: object): value is GoogleCloudGenerateRolesetKeyResponse {
    return true;
}

export function GoogleCloudGenerateRolesetKeyResponseFromJSON(json: any): GoogleCloudGenerateRolesetKeyResponse {
    return GoogleCloudGenerateRolesetKeyResponseFromJSONTyped(json, false);
}

export function GoogleCloudGenerateRolesetKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleCloudGenerateRolesetKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'key_algorithm': json['key_algorithm'] == null ? undefined : json['key_algorithm'],
        'key_type': json['key_type'] == null ? undefined : json['key_type'],
        'private_key_data': json['private_key_data'] == null ? undefined : json['private_key_data'],
    };
}

export function GoogleCloudGenerateRolesetKeyResponseToJSON(json: any): GoogleCloudGenerateRolesetKeyResponse {
    return GoogleCloudGenerateRolesetKeyResponseToJSONTyped(json, false);
}

export function GoogleCloudGenerateRolesetKeyResponseToJSONTyped(value?: GoogleCloudGenerateRolesetKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_algorithm': value['key_algorithm'],
        'key_type': value['key_type'],
        'private_key_data': value['private_key_data'],
    };
}

