/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleCloudKmsReadKeyConfigurationResponse
 */
export interface GoogleCloudKmsReadKeyConfigurationResponse {
    /**
     * Full Google Cloud KMS resource ID of the crypto key.
     * @type {string}
     * @memberof GoogleCloudKmsReadKeyConfigurationResponse
     */
    crypto_key?: string;
    /**
     * Maximum allowed crypto key version.
     * @type {number}
     * @memberof GoogleCloudKmsReadKeyConfigurationResponse
     */
    max_version?: number;
    /**
     * Minimum allowed crypto key version.
     * @type {number}
     * @memberof GoogleCloudKmsReadKeyConfigurationResponse
     */
    min_version?: number;
    /**
     * Name of the key in Vault.
     * @type {string}
     * @memberof GoogleCloudKmsReadKeyConfigurationResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the GoogleCloudKmsReadKeyConfigurationResponse interface.
 */
export function instanceOfGoogleCloudKmsReadKeyConfigurationResponse(value: object): value is GoogleCloudKmsReadKeyConfigurationResponse {
    return true;
}

export function GoogleCloudKmsReadKeyConfigurationResponseFromJSON(json: any): GoogleCloudKmsReadKeyConfigurationResponse {
    return GoogleCloudKmsReadKeyConfigurationResponseFromJSONTyped(json, false);
}

export function GoogleCloudKmsReadKeyConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleCloudKmsReadKeyConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'crypto_key': json['crypto_key'] == null ? undefined : json['crypto_key'],
        'max_version': json['max_version'] == null ? undefined : json['max_version'],
        'min_version': json['min_version'] == null ? undefined : json['min_version'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GoogleCloudKmsReadKeyConfigurationResponseToJSON(json: any): GoogleCloudKmsReadKeyConfigurationResponse {
    return GoogleCloudKmsReadKeyConfigurationResponseToJSONTyped(json, false);
}

export function GoogleCloudKmsReadKeyConfigurationResponseToJSONTyped(value?: GoogleCloudKmsReadKeyConfigurationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'crypto_key': value['crypto_key'],
        'max_version': value['max_version'],
        'min_version': value['min_version'],
        'name': value['name'],
    };
}

