/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupListByIdResponse
 */
export interface GroupListByIdResponse {
    /**
     * Entity details keyed by the entity id
     * @type {object}
     * @memberof GroupListByIdResponse
     */
    key_info?: object;
    /**
     * A list of entity ids
     * @type {Array<string>}
     * @memberof GroupListByIdResponse
     */
    keys?: Array<string>;
}

/**
 * Check if a given object implements the GroupListByIdResponse interface.
 */
export function instanceOfGroupListByIdResponse(value: object): value is GroupListByIdResponse {
    return true;
}

export function GroupListByIdResponseFromJSON(json: any): GroupListByIdResponse {
    return GroupListByIdResponseFromJSONTyped(json, false);
}

export function GroupListByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupListByIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'key_info': json['key_info'] == null ? undefined : json['key_info'],
        'keys': json['keys'] == null ? undefined : json['keys'],
    };
}

export function GroupListByIdResponseToJSON(json: any): GroupListByIdResponse {
    return GroupListByIdResponseToJSONTyped(json, false);
}

export function GroupListByIdResponseToJSONTyped(value?: GroupListByIdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_info': value['key_info'],
        'keys': value['keys'],
    };
}

