/**
 * Copyright IBM Corp. 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalClientActivityReportCountsResponse
 */
export interface InternalClientActivityReportCountsResponse {
    /**
     * A list of usage counts broken down by namespace. Each element is an object containing namespace name, counts, and mounts.
     * @type {Array<object>}
     * @memberof InternalClientActivityReportCountsResponse
     */
    by_namespace?: Array<object>;
    /**
     * The end time of the query interval.
     * @type {Date}
     * @memberof InternalClientActivityReportCountsResponse
     */
    end_time?: Date;
    /**
     * A list of objects, each representing monthly client count data.
     * @type {Array<object>}
     * @memberof InternalClientActivityReportCountsResponse
     */
    months?: Array<object>;
    /**
     * The start time of the query interval.
     * @type {Date}
     * @memberof InternalClientActivityReportCountsResponse
     */
    start_time?: Date;
    /**
     * Aggregated usage counts across all namespaces.
     * @type {object}
     * @memberof InternalClientActivityReportCountsResponse
     */
    total?: object;
}

/**
 * Check if a given object implements the InternalClientActivityReportCountsResponse interface.
 */
export function instanceOfInternalClientActivityReportCountsResponse(value: object): value is InternalClientActivityReportCountsResponse {
    return true;
}

export function InternalClientActivityReportCountsResponseFromJSON(json: any): InternalClientActivityReportCountsResponse {
    return InternalClientActivityReportCountsResponseFromJSONTyped(json, false);
}

export function InternalClientActivityReportCountsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalClientActivityReportCountsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'by_namespace': json['by_namespace'] == null ? undefined : json['by_namespace'],
        'end_time': json['end_time'] == null ? undefined : (new Date(json['end_time'])),
        'months': json['months'] == null ? undefined : json['months'],
        'start_time': json['start_time'] == null ? undefined : (new Date(json['start_time'])),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function InternalClientActivityReportCountsResponseToJSON(json: any): InternalClientActivityReportCountsResponse {
    return InternalClientActivityReportCountsResponseToJSONTyped(json, false);
}

export function InternalClientActivityReportCountsResponseToJSONTyped(value?: InternalClientActivityReportCountsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by_namespace': value['by_namespace'],
        'end_time': value['end_time'] == null ? undefined : ((value['end_time']).toISOString()),
        'months': value['months'],
        'start_time': value['start_time'] == null ? undefined : ((value['start_time']).toISOString()),
        'total': value['total'],
    };
}

