/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KmipCreateCaRequest
 */
export interface KmipCreateCaRequest {
    /**
     * CA key bits, valid values depend on key type
     * @type {number}
     * @memberof KmipCreateCaRequest
     */
    key_bits: number;
    /**
     * CA key type, rsa or ec
     * @type {string}
     * @memberof KmipCreateCaRequest
     */
    key_type: KmipCreateCaRequestKeyTypeEnum;
    /**
     * CA TTL in either an integer number of seconds (3600) or an integer time unit (1h)
     * @type {string}
     * @memberof KmipCreateCaRequest
     */
    ttl?: string;
}

/**
* @export
* @enum {string}
*/
export enum KmipCreateCaRequestKeyTypeEnum {
    RSA = 'rsa',
    EC = 'ec'
}


/**
 * Check if a given object implements the KmipCreateCaRequest interface.
 */
export function instanceOfKmipCreateCaRequest(value: object): value is KmipCreateCaRequest {
    if (!('key_bits' in value) || value['key_bits'] === undefined) return false;
    if (!('key_type' in value) || value['key_type'] === undefined) return false;
    return true;
}

export function KmipCreateCaRequestFromJSON(json: any): KmipCreateCaRequest {
    return KmipCreateCaRequestFromJSONTyped(json, false);
}

export function KmipCreateCaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KmipCreateCaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key_bits': json['key_bits'],
        'key_type': json['key_type'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
    };
}

export function KmipCreateCaRequestToJSON(json: any): KmipCreateCaRequest {
    return KmipCreateCaRequestToJSONTyped(json, false);
}

export function KmipCreateCaRequestToJSONTyped(value?: KmipCreateCaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_bits': value['key_bits'],
        'key_type': value['key_type'],
        'ttl': value['ttl'],
    };
}

