/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KubernetesWriteRoleRequest
 */
export interface KubernetesWriteRoleRequest {
    /**
     * A label selector for Kubernetes namespaces in which credentials can be generated. Accepts either a JSON or YAML object. If set with allowed_kubernetes_namespaces, the conditions are conjuncted.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    allowed_kubernetes_namespace_selector?: string;
    /**
     * A list of the Kubernetes namespaces in which credentials can be generated. If set to "*" all namespaces are allowed.
     * @type {Array<string>}
     * @memberof KubernetesWriteRoleRequest
     */
    allowed_kubernetes_namespaces?: Array<string>;
    /**
     * Additional annotations to apply to all generated Kubernetes objects.
     * @type {object}
     * @memberof KubernetesWriteRoleRequest
     */
    extra_annotations?: object;
    /**
     * Additional labels to apply to all generated Kubernetes objects.
     * @type {object}
     * @memberof KubernetesWriteRoleRequest
     */
    extra_labels?: object;
    /**
     * The Role or ClusterRole rules to use when generating a role. Accepts either a JSON or YAML object. If set, the entire chain of Kubernetes objects will be generated.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    generated_role_rules?: string;
    /**
     * The pre-existing Role or ClusterRole to bind a generated service account to. If set, Kubernetes token, service account, and role binding objects will be created.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    kubernetes_role_name?: string;
    /**
     * Specifies whether the Kubernetes role is a Role or ClusterRole.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    kubernetes_role_type?: string;
    /**
     * The name template to use when generating service accounts, roles and role bindings. If unset, a default template is used.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    name_template?: string;
    /**
     * The pre-existing service account to generate tokens for. Mutually exclusive with all role parameters. If set, only a Kubernetes service account token will be created.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    service_account_name?: string;
    /**
     * The default audiences for generated Kubernetes service account tokens. If not set or set to "", will use k8s cluster default.
     * @type {Array<string>}
     * @memberof KubernetesWriteRoleRequest
     */
    token_default_audiences?: Array<string>;
    /**
     * The default ttl for generated Kubernetes service account tokens. If not set or set to 0, will use system default.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    token_default_ttl?: string;
    /**
     * The maximum ttl for generated Kubernetes service account tokens. If not set or set to 0, will use system default.
     * @type {string}
     * @memberof KubernetesWriteRoleRequest
     */
    token_max_ttl?: string;
}

/**
 * Check if a given object implements the KubernetesWriteRoleRequest interface.
 */
export function instanceOfKubernetesWriteRoleRequest(value: object): value is KubernetesWriteRoleRequest {
    return true;
}

export function KubernetesWriteRoleRequestFromJSON(json: any): KubernetesWriteRoleRequest {
    return KubernetesWriteRoleRequestFromJSONTyped(json, false);
}

export function KubernetesWriteRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubernetesWriteRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed_kubernetes_namespace_selector': json['allowed_kubernetes_namespace_selector'] == null ? undefined : json['allowed_kubernetes_namespace_selector'],
        'allowed_kubernetes_namespaces': json['allowed_kubernetes_namespaces'] == null ? undefined : json['allowed_kubernetes_namespaces'],
        'extra_annotations': json['extra_annotations'] == null ? undefined : json['extra_annotations'],
        'extra_labels': json['extra_labels'] == null ? undefined : json['extra_labels'],
        'generated_role_rules': json['generated_role_rules'] == null ? undefined : json['generated_role_rules'],
        'kubernetes_role_name': json['kubernetes_role_name'] == null ? undefined : json['kubernetes_role_name'],
        'kubernetes_role_type': json['kubernetes_role_type'] == null ? undefined : json['kubernetes_role_type'],
        'name_template': json['name_template'] == null ? undefined : json['name_template'],
        'service_account_name': json['service_account_name'] == null ? undefined : json['service_account_name'],
        'token_default_audiences': json['token_default_audiences'] == null ? undefined : json['token_default_audiences'],
        'token_default_ttl': json['token_default_ttl'] == null ? undefined : json['token_default_ttl'],
        'token_max_ttl': json['token_max_ttl'] == null ? undefined : json['token_max_ttl'],
    };
}

export function KubernetesWriteRoleRequestToJSON(json: any): KubernetesWriteRoleRequest {
    return KubernetesWriteRoleRequestToJSONTyped(json, false);
}

export function KubernetesWriteRoleRequestToJSONTyped(value?: KubernetesWriteRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed_kubernetes_namespace_selector': value['allowed_kubernetes_namespace_selector'],
        'allowed_kubernetes_namespaces': value['allowed_kubernetes_namespaces'],
        'extra_annotations': value['extra_annotations'],
        'extra_labels': value['extra_labels'],
        'generated_role_rules': value['generated_role_rules'],
        'kubernetes_role_name': value['kubernetes_role_name'],
        'kubernetes_role_type': value['kubernetes_role_type'],
        'name_template': value['name_template'],
        'service_account_name': value['service_account_name'],
        'token_default_audiences': value['token_default_audiences'],
        'token_default_ttl': value['token_default_ttl'],
        'token_max_ttl': value['token_max_ttl'],
    };
}

