/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KvV1ListResponse
 */
export interface KvV1ListResponse {
    /**
     * List of keys at the requested path.
     * @type {Array<string>}
     * @memberof KvV1ListResponse
     */
    keys?: Array<string>;
}

/**
 * Check if a given object implements the KvV1ListResponse interface.
 */
export function instanceOfKvV1ListResponse(value: object): value is KvV1ListResponse {
    return true;
}

export function KvV1ListResponseFromJSON(json: any): KvV1ListResponse {
    return KvV1ListResponseFromJSONTyped(json, false);
}

export function KvV1ListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KvV1ListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': json['keys'] == null ? undefined : json['keys'],
    };
}

export function KvV1ListResponseToJSON(json: any): KvV1ListResponse {
    return KvV1ListResponseToJSONTyped(json, false);
}

export function KvV1ListResponseToJSONTyped(value?: KvV1ListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': value['keys'],
    };
}

