/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KvV2WriteResponse
 */
export interface KvV2WriteResponse {
    /**
     * 
     * @type {Date}
     * @memberof KvV2WriteResponse
     */
    created_time?: Date;
    /**
     * 
     * @type {object}
     * @memberof KvV2WriteResponse
     */
    custom_metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof KvV2WriteResponse
     */
    deletion_time?: string;
    /**
     * 
     * @type {boolean}
     * @memberof KvV2WriteResponse
     */
    destroyed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof KvV2WriteResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the KvV2WriteResponse interface.
 */
export function instanceOfKvV2WriteResponse(value: object): value is KvV2WriteResponse {
    return true;
}

export function KvV2WriteResponseFromJSON(json: any): KvV2WriteResponse {
    return KvV2WriteResponseFromJSONTyped(json, false);
}

export function KvV2WriteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KvV2WriteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created_time': json['created_time'] == null ? undefined : (new Date(json['created_time'])),
        'custom_metadata': json['custom_metadata'] == null ? undefined : json['custom_metadata'],
        'deletion_time': json['deletion_time'] == null ? undefined : json['deletion_time'],
        'destroyed': json['destroyed'] == null ? undefined : json['destroyed'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function KvV2WriteResponseToJSON(json: any): KvV2WriteResponse {
    return KvV2WriteResponseToJSONTyped(json, false);
}

export function KvV2WriteResponseToJSONTyped(value?: KvV2WriteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_time': value['created_time'] == null ? undefined : ((value['created_time']).toISOString()),
        'custom_metadata': value['custom_metadata'],
        'deletion_time': value['deletion_time'],
        'destroyed': value['destroyed'],
        'version': value['version'],
    };
}

