/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LdapMigrateRequest
 */
export interface LdapMigrateRequest {
    /**
     * Flag for whether to include role names in the static migration read information.
     * @type {boolean}
     * @memberof LdapMigrateRequest
     */
    include_role_names?: boolean;
}

/**
 * Check if a given object implements the LdapMigrateRequest interface.
 */
export function instanceOfLdapMigrateRequest(value: object): value is LdapMigrateRequest {
    return true;
}

export function LdapMigrateRequestFromJSON(json: any): LdapMigrateRequest {
    return LdapMigrateRequestFromJSONTyped(json, false);
}

export function LdapMigrateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LdapMigrateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'include_role_names': json['include_role_names'] == null ? undefined : json['include_role_names'],
    };
}

export function LdapMigrateRequestToJSON(json: any): LdapMigrateRequest {
    return LdapMigrateRequestToJSONTyped(json, false);
}

export function LdapMigrateRequestToJSONTyped(value?: LdapMigrateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'include_role_names': value['include_role_names'],
    };
}

