/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LdapWriteStaticRoleRequest
 */
export interface LdapWriteStaticRoleRequest {
    /**
     * If true, Vault will automatically unlock the account after a successful rotation. Overrides the mount-level auto_unlock setting for this role. If not set, the role inherits the mount-level setting.
     * @type {boolean}
     * @memberof LdapWriteStaticRoleRequest
     */
    auto_unlock?: boolean;
    /**
     * If set to true, will deregister all registered rotation jobs from the RotationManager for the plugin.
     * @type {boolean}
     * @memberof LdapWriteStaticRoleRequest
     */
    disable_automated_rotation?: boolean;
    /**
     * The distinguished name of the entry to manage. Required for self-managed static roles.
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    dn?: string;
    /**
     * Password for the static role. This is required for Vault to manage an existing account and enable rotation.
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    password?: string;
    /**
     * Password policy to use for this role. Overrides mount-level policy.
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    password_policy?: string;
    /**
     * If true, credentials will be rotated on read. If not set, inherits from engine configuration. Default: inherits from engine
     * @type {boolean}
     * @memberof LdapWriteStaticRoleRequest
     */
    rotate_on_read?: boolean;
    /**
     * Minimum time between rotate-on-read rotations. If not set, inherits from engine configuration.
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    rotate_on_read_cooldown?: string;
    /**
     * TTL for automatic credential rotation of the given username. Mutually exclusive with rotation_schedule
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    rotation_period?: string;
    /**
     * Defines the rotation policy to use when performing automated rotations.
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    rotation_policy?: string;
    /**
     * CRON-style string that will define the schedule on which rotations should occur. Mutually exclusive with rotation_period
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    rotation_schedule?: string;
    /**
     * Specifies the amount of time in which the rotation is allowed to occur starting from a given rotation_schedule
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    rotation_window?: string;
    /**
     * Skip the initial pasword rotation on import (has no effect on updates)
     * @type {boolean}
     * @memberof LdapWriteStaticRoleRequest
     */
    skip_import_rotation?: boolean;
    /**
     * The username/logon name for the entry with which this role will be associated.
     * @type {string}
     * @memberof LdapWriteStaticRoleRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the LdapWriteStaticRoleRequest interface.
 */
export function instanceOfLdapWriteStaticRoleRequest(value: object): value is LdapWriteStaticRoleRequest {
    return true;
}

export function LdapWriteStaticRoleRequestFromJSON(json: any): LdapWriteStaticRoleRequest {
    return LdapWriteStaticRoleRequestFromJSONTyped(json, false);
}

export function LdapWriteStaticRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LdapWriteStaticRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'auto_unlock': json['auto_unlock'] == null ? undefined : json['auto_unlock'],
        'disable_automated_rotation': json['disable_automated_rotation'] == null ? undefined : json['disable_automated_rotation'],
        'dn': json['dn'] == null ? undefined : json['dn'],
        'password': json['password'] == null ? undefined : json['password'],
        'password_policy': json['password_policy'] == null ? undefined : json['password_policy'],
        'rotate_on_read': json['rotate_on_read'] == null ? undefined : json['rotate_on_read'],
        'rotate_on_read_cooldown': json['rotate_on_read_cooldown'] == null ? undefined : json['rotate_on_read_cooldown'],
        'rotation_period': json['rotation_period'] == null ? undefined : json['rotation_period'],
        'rotation_policy': json['rotation_policy'] == null ? undefined : json['rotation_policy'],
        'rotation_schedule': json['rotation_schedule'] == null ? undefined : json['rotation_schedule'],
        'rotation_window': json['rotation_window'] == null ? undefined : json['rotation_window'],
        'skip_import_rotation': json['skip_import_rotation'] == null ? undefined : json['skip_import_rotation'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function LdapWriteStaticRoleRequestToJSON(json: any): LdapWriteStaticRoleRequest {
    return LdapWriteStaticRoleRequestToJSONTyped(json, false);
}

export function LdapWriteStaticRoleRequestToJSONTyped(value?: LdapWriteStaticRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auto_unlock': value['auto_unlock'],
        'disable_automated_rotation': value['disable_automated_rotation'],
        'dn': value['dn'],
        'password': value['password'],
        'password_policy': value['password_policy'],
        'rotate_on_read': value['rotate_on_read'],
        'rotate_on_read_cooldown': value['rotate_on_read_cooldown'],
        'rotation_period': value['rotation_period'],
        'rotation_policy': value['rotation_policy'],
        'rotation_schedule': value['rotation_schedule'],
        'rotation_window': value['rotation_window'],
        'skip_import_rotation': value['skip_import_rotation'],
        'username': value['username'],
    };
}

