/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MfaSelfEnrollRequest
 */
export interface MfaSelfEnrollRequest {
    /**
     * The ID of the TOTP MFA method to generate a credential for.
     * @type {string}
     * @memberof MfaSelfEnrollRequest
     */
    mfa_method_id: string;
    /**
     * MFA request ID returned from the initial login attempt that triggered the MFA requirement.
     * @type {string}
     * @memberof MfaSelfEnrollRequest
     */
    mfa_request_id: string;
}

/**
 * Check if a given object implements the MfaSelfEnrollRequest interface.
 */
export function instanceOfMfaSelfEnrollRequest(value: object): value is MfaSelfEnrollRequest {
    if (!('mfa_method_id' in value) || value['mfa_method_id'] === undefined) return false;
    if (!('mfa_request_id' in value) || value['mfa_request_id'] === undefined) return false;
    return true;
}

export function MfaSelfEnrollRequestFromJSON(json: any): MfaSelfEnrollRequest {
    return MfaSelfEnrollRequestFromJSONTyped(json, false);
}

export function MfaSelfEnrollRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MfaSelfEnrollRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mfa_method_id': json['mfa_method_id'],
        'mfa_request_id': json['mfa_request_id'],
    };
}

export function MfaSelfEnrollRequestToJSON(json: any): MfaSelfEnrollRequest {
    return MfaSelfEnrollRequestToJSONTyped(json, false);
}

export function MfaSelfEnrollRequestToJSONTyped(value?: MfaSelfEnrollRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mfa_method_id': value['mfa_method_id'],
        'mfa_request_id': value['mfa_request_id'],
    };
}

