/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MfaValidateRequest
 */
export interface MfaValidateRequest {
    /**
     * A map from MFA method ID to a slice of passcodes or an empty slice if the method does not use passcodes
     * @type {object}
     * @memberof MfaValidateRequest
     */
    mfa_payload: object;
    /**
     * ID for this MFA request
     * @type {string}
     * @memberof MfaValidateRequest
     */
    mfa_request_id: string;
}

/**
 * Check if a given object implements the MfaValidateRequest interface.
 */
export function instanceOfMfaValidateRequest(value: object): value is MfaValidateRequest {
    if (!('mfa_payload' in value) || value['mfa_payload'] === undefined) return false;
    if (!('mfa_request_id' in value) || value['mfa_request_id'] === undefined) return false;
    return true;
}

export function MfaValidateRequestFromJSON(json: any): MfaValidateRequest {
    return MfaValidateRequestFromJSONTyped(json, false);
}

export function MfaValidateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MfaValidateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mfa_payload': json['mfa_payload'],
        'mfa_request_id': json['mfa_request_id'],
    };
}

export function MfaValidateRequestToJSON(json: any): MfaValidateRequest {
    return MfaValidateRequestToJSONTyped(json, false);
}

export function MfaValidateRequestToJSONTyped(value?: MfaValidateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mfa_payload': value['mfa_payload'],
        'mfa_request_id': value['mfa_request_id'],
    };
}

