/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthResourceServerReadProfileByIdResponse
 */
export interface OauthResourceServerReadProfileByIdResponse {
    /**
     * List of allowed audiences (aud claim).
     * @type {Array<string>}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    audiences?: Array<string>;
    /**
     * Leeway for clock skew in seconds.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    clock_skew_leeway?: string;
    /**
     * Stable unique identifier for this OAuth Resource Server Configuration profile.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    config_id?: string;
    /**
     * Whether this profile is enabled for JWT validation.
     * @type {boolean}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    enabled?: boolean;
    /**
     * The issuer ID (iss claim) to validate against.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    issuer_id?: string;
    /**
     * Optional CA certificate for JWKS URI TLS validation.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    jwks_ca_pem?: string;
    /**
     * The JWKS URI to fetch public keys from.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    jwks_uri?: string;
    /**
     * The JWT type: 'access_token' or 'transaction_token'.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    jwt_type?: string;
    /**
     * If true, JWT-authenticated tokens omit the default policy unless it is applied elsewhere.
     * @type {boolean}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    no_default_policy?: boolean;
    /**
     * If true, authorization_details claim is optional for OAuth 2.0 JWTs using this OAuth resource server.
     * @type {boolean}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    optional_authorization_details?: boolean;
    /**
     * The name of the OAuth Resource Server Configuration profile.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    profile_name?: string;
    /**
     * List of static public keys with key_id and pem fields.
     * @type {Array<object>}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    public_keys?: Array<object>;
    /**
     * List of supported signing algorithms.
     * @type {Array<string>}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    supported_algorithms?: Array<string>;
    /**
     * If true, use JWKS URI for key validation.
     * @type {boolean}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    use_jwks?: boolean;
    /**
     * The claim to use as the user identifier.
     * @type {string}
     * @memberof OauthResourceServerReadProfileByIdResponse
     */
    user_claim?: string;
}

/**
 * Check if a given object implements the OauthResourceServerReadProfileByIdResponse interface.
 */
export function instanceOfOauthResourceServerReadProfileByIdResponse(value: object): value is OauthResourceServerReadProfileByIdResponse {
    return true;
}

export function OauthResourceServerReadProfileByIdResponseFromJSON(json: any): OauthResourceServerReadProfileByIdResponse {
    return OauthResourceServerReadProfileByIdResponseFromJSONTyped(json, false);
}

export function OauthResourceServerReadProfileByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthResourceServerReadProfileByIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'audiences': json['audiences'] == null ? undefined : json['audiences'],
        'clock_skew_leeway': json['clock_skew_leeway'] == null ? undefined : json['clock_skew_leeway'],
        'config_id': json['config_id'] == null ? undefined : json['config_id'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'issuer_id': json['issuer_id'] == null ? undefined : json['issuer_id'],
        'jwks_ca_pem': json['jwks_ca_pem'] == null ? undefined : json['jwks_ca_pem'],
        'jwks_uri': json['jwks_uri'] == null ? undefined : json['jwks_uri'],
        'jwt_type': json['jwt_type'] == null ? undefined : json['jwt_type'],
        'no_default_policy': json['no_default_policy'] == null ? undefined : json['no_default_policy'],
        'optional_authorization_details': json['optional_authorization_details'] == null ? undefined : json['optional_authorization_details'],
        'profile_name': json['profile_name'] == null ? undefined : json['profile_name'],
        'public_keys': json['public_keys'] == null ? undefined : json['public_keys'],
        'supported_algorithms': json['supported_algorithms'] == null ? undefined : json['supported_algorithms'],
        'use_jwks': json['use_jwks'] == null ? undefined : json['use_jwks'],
        'user_claim': json['user_claim'] == null ? undefined : json['user_claim'],
    };
}

export function OauthResourceServerReadProfileByIdResponseToJSON(json: any): OauthResourceServerReadProfileByIdResponse {
    return OauthResourceServerReadProfileByIdResponseToJSONTyped(json, false);
}

export function OauthResourceServerReadProfileByIdResponseToJSONTyped(value?: OauthResourceServerReadProfileByIdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audiences': value['audiences'],
        'clock_skew_leeway': value['clock_skew_leeway'],
        'config_id': value['config_id'],
        'enabled': value['enabled'],
        'issuer_id': value['issuer_id'],
        'jwks_ca_pem': value['jwks_ca_pem'],
        'jwks_uri': value['jwks_uri'],
        'jwt_type': value['jwt_type'],
        'no_default_policy': value['no_default_policy'],
        'optional_authorization_details': value['optional_authorization_details'],
        'profile_name': value['profile_name'],
        'public_keys': value['public_keys'],
        'supported_algorithms': value['supported_algorithms'],
        'use_jwks': value['use_jwks'],
        'user_claim': value['user_claim'],
    };
}

