/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchRequest
 */
export interface PatchRequest {
    /**
     * A comma-separated list of attribute names to include in the response.
     * @type {Array<string>}
     * @memberof PatchRequest
     */
    attributes?: Array<string>;
    /**
     * The desired number of results per page.
     * @type {number}
     * @memberof PatchRequest
     */
    count?: number;
    /**
     * A comma-separated list of attribute names to exclude from the response.
     * @type {Array<string>}
     * @memberof PatchRequest
     */
    excludedAttributes?: Array<string>;
    /**
     * The 1-based index of the first result to return.
     * @type {number}
     * @memberof PatchRequest
     */
    startIndex?: number;
}

/**
 * Check if a given object implements the PatchRequest interface.
 */
export function instanceOfPatchRequest(value: object): value is PatchRequest {
    return true;
}

export function PatchRequestFromJSON(json: any): PatchRequest {
    return PatchRequestFromJSONTyped(json, false);
}

export function PatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'count': json['count'] == null ? undefined : json['count'],
        'excludedAttributes': json['excludedAttributes'] == null ? undefined : json['excludedAttributes'],
        'startIndex': json['startIndex'] == null ? undefined : json['startIndex'],
    };
}

export function PatchRequestToJSON(json: any): PatchRequest {
    return PatchRequestToJSONTyped(json, false);
}

export function PatchRequestToJSONTyped(value?: PatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'],
        'count': value['count'],
        'excludedAttributes': value['excludedAttributes'],
        'startIndex': value['startIndex'],
    };
}

