/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiExternalCaWriteRoleNewOrderRequest
 */
export interface PkiExternalCaWriteRoleNewOrderRequest {
    /**
     * CSR containing identifiers for the new order
     * @type {string}
     * @memberof PkiExternalCaWriteRoleNewOrderRequest
     */
    csr?: string;
    /**
     * List of identifiers for the new order
     * @type {Array<string>}
     * @memberof PkiExternalCaWriteRoleNewOrderRequest
     */
    identifiers?: Array<string>;
}

/**
 * Check if a given object implements the PkiExternalCaWriteRoleNewOrderRequest interface.
 */
export function instanceOfPkiExternalCaWriteRoleNewOrderRequest(value: object): value is PkiExternalCaWriteRoleNewOrderRequest {
    return true;
}

export function PkiExternalCaWriteRoleNewOrderRequestFromJSON(json: any): PkiExternalCaWriteRoleNewOrderRequest {
    return PkiExternalCaWriteRoleNewOrderRequestFromJSONTyped(json, false);
}

export function PkiExternalCaWriteRoleNewOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiExternalCaWriteRoleNewOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'csr': json['csr'] == null ? undefined : json['csr'],
        'identifiers': json['identifiers'] == null ? undefined : json['identifiers'],
    };
}

export function PkiExternalCaWriteRoleNewOrderRequestToJSON(json: any): PkiExternalCaWriteRoleNewOrderRequest {
    return PkiExternalCaWriteRoleNewOrderRequestToJSONTyped(json, false);
}

export function PkiExternalCaWriteRoleNewOrderRequestToJSONTyped(value?: PkiExternalCaWriteRoleNewOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'csr': value['csr'],
        'identifiers': value['identifiers'],
    };
}

