/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiExternalCaReadConfigDnsAzureDnsResponse
 */
export interface PkiExternalCaReadConfigDnsAzureDnsResponse {
    /**
     * Azure service principal client ID
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    client_id?: string;
    /**
     * Configuration creation timestamp
     * @type {Date}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    creation_date?: Date;
    /**
     * Azure cloud environment (AzurePublic, AzureChina, AzureGovernment; default: AzurePublic)
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    environment?: string;
    /**
     * List of DNS identifiers this provider can be used for. Supports wildcard patterns with leftmost * (e.g., *.example.com)
     * @type {Array<string>}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    identifiers?: Array<string>;
    /**
     * Configuration last update timestamp
     * @type {Date}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    last_update_date?: Date;
    /**
     * Name of the azure-dns DNS configuration
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    name?: string;
    /**
     * Azure resource group name containing the DNS zone
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    resource_group_name?: string;
    /**
     * Azure subscription ID
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    subscription_id?: string;
    /**
     * Azure tenant ID
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    tenant_id?: string;
    /**
     * TTL for DNS TXT records used in DNS-01 challenges
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    ttl?: string;
    /**
     * Azure DNS zone name
     * @type {string}
     * @memberof PkiExternalCaReadConfigDnsAzureDnsResponse
     */
    zone_name?: string;
}

/**
 * Check if a given object implements the PkiExternalCaReadConfigDnsAzureDnsResponse interface.
 */
export function instanceOfPkiExternalCaReadConfigDnsAzureDnsResponse(value: object): value is PkiExternalCaReadConfigDnsAzureDnsResponse {
    return true;
}

export function PkiExternalCaReadConfigDnsAzureDnsResponseFromJSON(json: any): PkiExternalCaReadConfigDnsAzureDnsResponse {
    return PkiExternalCaReadConfigDnsAzureDnsResponseFromJSONTyped(json, false);
}

export function PkiExternalCaReadConfigDnsAzureDnsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiExternalCaReadConfigDnsAzureDnsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'creation_date': json['creation_date'] == null ? undefined : (new Date(json['creation_date'])),
        'environment': json['environment'] == null ? undefined : json['environment'],
        'identifiers': json['identifiers'] == null ? undefined : json['identifiers'],
        'last_update_date': json['last_update_date'] == null ? undefined : (new Date(json['last_update_date'])),
        'name': json['name'] == null ? undefined : json['name'],
        'resource_group_name': json['resource_group_name'] == null ? undefined : json['resource_group_name'],
        'subscription_id': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'tenant_id': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'zone_name': json['zone_name'] == null ? undefined : json['zone_name'],
    };
}

export function PkiExternalCaReadConfigDnsAzureDnsResponseToJSON(json: any): PkiExternalCaReadConfigDnsAzureDnsResponse {
    return PkiExternalCaReadConfigDnsAzureDnsResponseToJSONTyped(json, false);
}

export function PkiExternalCaReadConfigDnsAzureDnsResponseToJSONTyped(value?: PkiExternalCaReadConfigDnsAzureDnsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['client_id'],
        'creation_date': value['creation_date'] == null ? undefined : ((value['creation_date']).toISOString()),
        'environment': value['environment'],
        'identifiers': value['identifiers'],
        'last_update_date': value['last_update_date'] == null ? undefined : ((value['last_update_date']).toISOString()),
        'name': value['name'],
        'resource_group_name': value['resource_group_name'],
        'subscription_id': value['subscription_id'],
        'tenant_id': value['tenant_id'],
        'ttl': value['ttl'],
        'zone_name': value['zone_name'],
    };
}

