/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiExternalCaListLookupOrdersRecentResponse
 */
export interface PkiExternalCaListLookupOrdersRecentResponse {
    /**
     * Key info with order metadata.
     * @type {object}
     * @memberof PkiExternalCaListLookupOrdersRecentResponse
     */
    key_info?: object;
    /**
     * A list of order IDs
     * @type {Array<string>}
     * @memberof PkiExternalCaListLookupOrdersRecentResponse
     */
    keys?: Array<string>;
}

/**
 * Check if a given object implements the PkiExternalCaListLookupOrdersRecentResponse interface.
 */
export function instanceOfPkiExternalCaListLookupOrdersRecentResponse(value: object): value is PkiExternalCaListLookupOrdersRecentResponse {
    return true;
}

export function PkiExternalCaListLookupOrdersRecentResponseFromJSON(json: any): PkiExternalCaListLookupOrdersRecentResponse {
    return PkiExternalCaListLookupOrdersRecentResponseFromJSONTyped(json, false);
}

export function PkiExternalCaListLookupOrdersRecentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiExternalCaListLookupOrdersRecentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'key_info': json['key_info'] == null ? undefined : json['key_info'],
        'keys': json['keys'] == null ? undefined : json['keys'],
    };
}

export function PkiExternalCaListLookupOrdersRecentResponseToJSON(json: any): PkiExternalCaListLookupOrdersRecentResponse {
    return PkiExternalCaListLookupOrdersRecentResponseToJSONTyped(json, false);
}

export function PkiExternalCaListLookupOrdersRecentResponseToJSONTyped(value?: PkiExternalCaListLookupOrdersRecentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_info': value['key_info'],
        'keys': value['keys'],
    };
}

