/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiExternalCaReadRoleOrderFetchCertResponse
 */
export interface PkiExternalCaReadRoleOrderFetchCertResponse {
    /**
     * Authority key identifier
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    authority_key_id?: string;
    /**
     * CA certificate chain
     * @type {Array<string>}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    ca_chain?: Array<string>;
    /**
     * The certificate in the requested format
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    certificate?: string;
    /**
     * Format of the returned certificate
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    certificate_format?: string;
    /**
     * Certificate validity end time (RFC3339)
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    not_after?: string;
    /**
     * Certificate validity start time (RFC3339)
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    not_before?: string;
    /**
     * Private key (only for identifier-based workflows)
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    private_key?: string;
    /**
     * Private key type (only for identifier-based workflows)
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    private_key_type?: string;
    /**
     * Certificate serial number
     * @type {string}
     * @memberof PkiExternalCaReadRoleOrderFetchCertResponse
     */
    serial_number?: string;
}

/**
 * Check if a given object implements the PkiExternalCaReadRoleOrderFetchCertResponse interface.
 */
export function instanceOfPkiExternalCaReadRoleOrderFetchCertResponse(value: object): value is PkiExternalCaReadRoleOrderFetchCertResponse {
    return true;
}

export function PkiExternalCaReadRoleOrderFetchCertResponseFromJSON(json: any): PkiExternalCaReadRoleOrderFetchCertResponse {
    return PkiExternalCaReadRoleOrderFetchCertResponseFromJSONTyped(json, false);
}

export function PkiExternalCaReadRoleOrderFetchCertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiExternalCaReadRoleOrderFetchCertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authority_key_id': json['authority_key_id'] == null ? undefined : json['authority_key_id'],
        'ca_chain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'certificate_format': json['certificate_format'] == null ? undefined : json['certificate_format'],
        'not_after': json['not_after'] == null ? undefined : json['not_after'],
        'not_before': json['not_before'] == null ? undefined : json['not_before'],
        'private_key': json['private_key'] == null ? undefined : json['private_key'],
        'private_key_type': json['private_key_type'] == null ? undefined : json['private_key_type'],
        'serial_number': json['serial_number'] == null ? undefined : json['serial_number'],
    };
}

export function PkiExternalCaReadRoleOrderFetchCertResponseToJSON(json: any): PkiExternalCaReadRoleOrderFetchCertResponse {
    return PkiExternalCaReadRoleOrderFetchCertResponseToJSONTyped(json, false);
}

export function PkiExternalCaReadRoleOrderFetchCertResponseToJSONTyped(value?: PkiExternalCaReadRoleOrderFetchCertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authority_key_id': value['authority_key_id'],
        'ca_chain': value['ca_chain'],
        'certificate': value['certificate'],
        'certificate_format': value['certificate_format'],
        'not_after': value['not_after'],
        'not_before': value['not_before'],
        'private_key': value['private_key'],
        'private_key_type': value['private_key_type'],
        'serial_number': value['serial_number'],
    };
}

