/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest
 */
export interface PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest {
    /**
     * Force the rotation of an account if orders are still pending
     * @type {boolean}
     * @memberof PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest
     */
    force?: boolean;
    /**
     * Key type to generate for the new account key
     * @type {string}
     * @memberof PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest
     */
    key_type?: PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestKeyTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestKeyTypeEnum {
    EC_256 = 'ec-256',
    EC_384 = 'ec-384',
    EC_521 = 'ec-521',
    RSA_2048 = 'rsa-2048',
    RSA_4096 = 'rsa-4096',
    RSA_8192 = 'rsa-8192'
}


/**
 * Check if a given object implements the PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest interface.
 */
export function instanceOfPkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest(value: object): value is PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest {
    return true;
}

export function PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestFromJSON(json: any): PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest {
    return PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestFromJSONTyped(json, false);
}

export function PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'force': json['force'] == null ? undefined : json['force'],
        'key_type': json['key_type'] == null ? undefined : json['key_type'],
    };
}

export function PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestToJSON(json: any): PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest {
    return PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestToJSONTyped(json, false);
}

export function PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequestToJSONTyped(value?: PkiExternalCaWriteConfigAcmeAccountNameRotateKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'force': value['force'],
        'key_type': value['key_type'],
    };
}

