/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiExternalCaWriteDnsTestWorkflowRequest
 */
export interface PkiExternalCaWriteDnsTestWorkflowRequest {
    /**
     * The DNS identifier (domain name) to test with
     * @type {string}
     * @memberof PkiExternalCaWriteDnsTestWorkflowRequest
     */
    identifier: string;
    /**
     * Do not perform any cleanup operations, useful for testing and manual validation a record was created within the DNS provider
     * @type {boolean}
     * @memberof PkiExternalCaWriteDnsTestWorkflowRequest
     */
    omit_cleanup?: boolean;
    /**
     * The name of the DNS provider configuration to test
     * @type {string}
     * @memberof PkiExternalCaWriteDnsTestWorkflowRequest
     */
    provider_name: string;
    /**
     * The DNS provider type
     * @type {string}
     * @memberof PkiExternalCaWriteDnsTestWorkflowRequest
     */
    provider_type: string;
}

/**
 * Check if a given object implements the PkiExternalCaWriteDnsTestWorkflowRequest interface.
 */
export function instanceOfPkiExternalCaWriteDnsTestWorkflowRequest(value: object): value is PkiExternalCaWriteDnsTestWorkflowRequest {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('provider_name' in value) || value['provider_name'] === undefined) return false;
    if (!('provider_type' in value) || value['provider_type'] === undefined) return false;
    return true;
}

export function PkiExternalCaWriteDnsTestWorkflowRequestFromJSON(json: any): PkiExternalCaWriteDnsTestWorkflowRequest {
    return PkiExternalCaWriteDnsTestWorkflowRequestFromJSONTyped(json, false);
}

export function PkiExternalCaWriteDnsTestWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiExternalCaWriteDnsTestWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'omit_cleanup': json['omit_cleanup'] == null ? undefined : json['omit_cleanup'],
        'provider_name': json['provider_name'],
        'provider_type': json['provider_type'],
    };
}

export function PkiExternalCaWriteDnsTestWorkflowRequestToJSON(json: any): PkiExternalCaWriteDnsTestWorkflowRequest {
    return PkiExternalCaWriteDnsTestWorkflowRequestToJSONTyped(json, false);
}

export function PkiExternalCaWriteDnsTestWorkflowRequestToJSONTyped(value?: PkiExternalCaWriteDnsTestWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'omit_cleanup': value['omit_cleanup'],
        'provider_name': value['provider_name'],
        'provider_type': value['provider_type'],
    };
}

