/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiGenerateInternalKeyResponse
 */
export interface PkiGenerateInternalKeyResponse {
    /**
     * ID assigned to this key.
     * @type {string}
     * @memberof PkiGenerateInternalKeyResponse
     */
    key_id?: string;
    /**
     * Name assigned to this key.
     * @type {string}
     * @memberof PkiGenerateInternalKeyResponse
     */
    key_name?: string;
    /**
     * The type of key to use; defaults to RSA. "rsa" "ec" and "ed25519" are the only valid values.
     * @type {string}
     * @memberof PkiGenerateInternalKeyResponse
     */
    key_type?: string;
    /**
     * The private key string
     * @type {string}
     * @memberof PkiGenerateInternalKeyResponse
     */
    private_key?: string;
}

/**
 * Check if a given object implements the PkiGenerateInternalKeyResponse interface.
 */
export function instanceOfPkiGenerateInternalKeyResponse(value: object): value is PkiGenerateInternalKeyResponse {
    return true;
}

export function PkiGenerateInternalKeyResponseFromJSON(json: any): PkiGenerateInternalKeyResponse {
    return PkiGenerateInternalKeyResponseFromJSONTyped(json, false);
}

export function PkiGenerateInternalKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiGenerateInternalKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'key_id': json['key_id'] == null ? undefined : json['key_id'],
        'key_name': json['key_name'] == null ? undefined : json['key_name'],
        'key_type': json['key_type'] == null ? undefined : json['key_type'],
        'private_key': json['private_key'] == null ? undefined : json['private_key'],
    };
}

export function PkiGenerateInternalKeyResponseToJSON(json: any): PkiGenerateInternalKeyResponse {
    return PkiGenerateInternalKeyResponseToJSONTyped(json, false);
}

export function PkiGenerateInternalKeyResponseToJSONTyped(value?: PkiGenerateInternalKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_id': value['key_id'],
        'key_name': value['key_name'],
        'key_type': value['key_type'],
        'private_key': value['private_key'],
    };
}

