/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiGenerateKmsKeyRequest
 */
export interface PkiGenerateKmsKeyRequest {
    /**
     * The number of bits to use. Allowed values are 0 (universal default); with rsa key_type: 2048 (default), 3072, 4096 or 8192; with ec key_type: 224, 256 (default), 384, or 521; ignored with ed25519.
     * @type {number}
     * @memberof PkiGenerateKmsKeyRequest
     */
    key_bits?: number;
    /**
     * Optional name to be used for this key
     * @type {string}
     * @memberof PkiGenerateKmsKeyRequest
     */
    key_name?: string;
    /**
     * The type of key to use; defaults to RSA. "rsa" "ec" and "ed25519" are the only valid values.
     * @type {string}
     * @memberof PkiGenerateKmsKeyRequest
     */
    key_type?: PkiGenerateKmsKeyRequestKeyTypeEnum;
    /**
     * The name of the managed key to use when the exported type is kms. When kms type is the key type, this field or managed_key_name is required. Ignored for other types.
     * @type {string}
     * @memberof PkiGenerateKmsKeyRequest
     */
    managed_key_id?: string;
    /**
     * The name of the managed key to use when the exported type is kms. When kms type is the key type, this field or managed_key_id is required. Ignored for other types.
     * @type {string}
     * @memberof PkiGenerateKmsKeyRequest
     */
    managed_key_name?: string;
}

/**
* @export
* @enum {string}
*/
export enum PkiGenerateKmsKeyRequestKeyTypeEnum {
    RSA = 'rsa',
    EC = 'ec',
    ED25519 = 'ed25519'
}


/**
 * Check if a given object implements the PkiGenerateKmsKeyRequest interface.
 */
export function instanceOfPkiGenerateKmsKeyRequest(value: object): value is PkiGenerateKmsKeyRequest {
    return true;
}

export function PkiGenerateKmsKeyRequestFromJSON(json: any): PkiGenerateKmsKeyRequest {
    return PkiGenerateKmsKeyRequestFromJSONTyped(json, false);
}

export function PkiGenerateKmsKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiGenerateKmsKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key_bits': json['key_bits'] == null ? undefined : json['key_bits'],
        'key_name': json['key_name'] == null ? undefined : json['key_name'],
        'key_type': json['key_type'] == null ? undefined : json['key_type'],
        'managed_key_id': json['managed_key_id'] == null ? undefined : json['managed_key_id'],
        'managed_key_name': json['managed_key_name'] == null ? undefined : json['managed_key_name'],
    };
}

export function PkiGenerateKmsKeyRequestToJSON(json: any): PkiGenerateKmsKeyRequest {
    return PkiGenerateKmsKeyRequestToJSONTyped(json, false);
}

export function PkiGenerateKmsKeyRequestToJSONTyped(value?: PkiGenerateKmsKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_bits': value['key_bits'],
        'key_name': value['key_name'],
        'key_type': value['key_type'],
        'managed_key_id': value['managed_key_id'],
        'managed_key_name': value['managed_key_name'],
    };
}

