/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiIssuerIssueWithRoleRequest
 */
export interface PkiIssuerIssueWithRoleRequest {
    /**
     * The requested Subject Alternative Names, if any, in a comma-delimited list. If email protection is enabled for the role, this may contain email addresses.
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    alt_names?: string;
    /**
     * User supplied metadata to store associated with this certificate's serial number, base64 encoded
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    cert_metadata?: string;
    /**
     * The requested common name; if you want more than one, specify the alternative names in the alt_names map. If email protection is enabled in the role, this may be an email address.
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    common_name?: string;
    /**
     * If true, the Common Name will not be included in DNS or Email Subject Alternate Names. Defaults to false (CN is included).
     * @type {boolean}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    exclude_cn_from_sans?: boolean;
    /**
     * Format for returned data. Can be "pem", "der", "pem_bundle", "pkcs12_bundle" or "jks_bundle". If "pem_bundle", any private key and issuing cert will be appended to the certificate pem. Formats "der", "pkcs12_bundle" or "jks_bundle" are base64 encoded. Defaults to "pem".
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    format?: PkiIssuerIssueWithRoleRequestFormatEnum;
    /**
     * The requested IP SANs, if any, in a comma-delimited list
     * @type {Array<string>}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    ip_sans?: Array<string>;
    /**
     * The entry alias in the Java keystore (JKS) when format is set to "jks_bundle" and bundle contains a single PrivateKeyEntry. This field is case-sensitive, but relying on case-only differences for unique aliases is not recommended. Defaults to "1". This parameter is ignored by endpoints that return multiple TrustedCertificateEntry values (trust stores), and entry aliases are assigned incrementing numeric strings starting at "1".
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    jks_alias?: string;
    /**
     * Password for encrypting the Java keystore when format is set to "jks_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    jks_password?: string;
    /**
     * Set the not after field of the certificate with specified date value. The value format should be given in UTC format YYYY-MM-ddTHH:MM:SSZ
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    not_after?: string;
    /**
     * Requested other SANs, in an array with the format <oid>;UTF8:<utf8 string value> for each entry.
     * @type {Array<string>}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    other_sans?: Array<string>;
    /**
     * Encoder profile to use for PKCS#12 archives when format is set to "pkcs12_bundle". Valid values are "modern2026" and "modern2023". Defaults to "modern2026", which uses the newer PKCS#12 integrity format (PBMAC1).
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    pkcs12_encoder?: PkiIssuerIssueWithRoleRequestPkcs12EncoderEnum;
    /**
     * Password for encrypting the PKCS#12 archive when format is set to "pkcs12_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    pkcs12_password?: string;
    /**
     * Format for the returned private key. Generally the default will be controlled by the "format" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to "pkcs8" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to "der".
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    private_key_format?: PkiIssuerIssueWithRoleRequestPrivateKeyFormatEnum;
    /**
     * Whether or not to remove self-signed CA certificates in the output of the ca_chain field.
     * @type {boolean}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    remove_roots_from_chain?: boolean;
    /**
     * The Subject's requested serial number, if any. See RFC 4519 Section 2.31 'serialNumber' for a description of this field. If you want more than one, specify alternative names in the alt_names map using OID 2.5.4.5. This has no impact on the final certificate's Serial Number field.
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    serial_number?: string;
    /**
     * The requested Time To Live for the certificate; sets the expiration date. If not specified the role default, backend default, or system default TTL is used, in that order. Cannot be larger than the role max TTL.
     * @type {string}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    ttl?: string;
    /**
     * The requested URI SANs, if any, in a comma-delimited list.
     * @type {Array<string>}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    uri_sans?: Array<string>;
    /**
     * The requested user_ids value to place in the subject, if any, in a comma-delimited list. Restricted by allowed_user_ids. Any values are added with OID 0.9.2342.19200300.100.1.1.
     * @type {Array<string>}
     * @memberof PkiIssuerIssueWithRoleRequest
     */
    user_ids?: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum PkiIssuerIssueWithRoleRequestFormatEnum {
    PEM = 'pem',
    DER = 'der',
    PEM_BUNDLE = 'pem_bundle',
    PKCS12_BUNDLE = 'pkcs12_bundle',
    JKS_BUNDLE = 'jks_bundle'
}
/**
* @export
* @enum {string}
*/
export enum PkiIssuerIssueWithRoleRequestPkcs12EncoderEnum {
    MODERN2026 = 'modern2026',
    MODERN2023 = 'modern2023'
}
/**
* @export
* @enum {string}
*/
export enum PkiIssuerIssueWithRoleRequestPrivateKeyFormatEnum {
    EMPTY = '',
    DER = 'der',
    PEM = 'pem',
    PKCS8 = 'pkcs8'
}


/**
 * Check if a given object implements the PkiIssuerIssueWithRoleRequest interface.
 */
export function instanceOfPkiIssuerIssueWithRoleRequest(value: object): value is PkiIssuerIssueWithRoleRequest {
    return true;
}

export function PkiIssuerIssueWithRoleRequestFromJSON(json: any): PkiIssuerIssueWithRoleRequest {
    return PkiIssuerIssueWithRoleRequestFromJSONTyped(json, false);
}

export function PkiIssuerIssueWithRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiIssuerIssueWithRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alt_names': json['alt_names'] == null ? undefined : json['alt_names'],
        'cert_metadata': json['cert_metadata'] == null ? undefined : json['cert_metadata'],
        'common_name': json['common_name'] == null ? undefined : json['common_name'],
        'exclude_cn_from_sans': json['exclude_cn_from_sans'] == null ? undefined : json['exclude_cn_from_sans'],
        'format': json['format'] == null ? undefined : json['format'],
        'ip_sans': json['ip_sans'] == null ? undefined : json['ip_sans'],
        'jks_alias': json['jks_alias'] == null ? undefined : json['jks_alias'],
        'jks_password': json['jks_password'] == null ? undefined : json['jks_password'],
        'not_after': json['not_after'] == null ? undefined : json['not_after'],
        'other_sans': json['other_sans'] == null ? undefined : json['other_sans'],
        'pkcs12_encoder': json['pkcs12_encoder'] == null ? undefined : json['pkcs12_encoder'],
        'pkcs12_password': json['pkcs12_password'] == null ? undefined : json['pkcs12_password'],
        'private_key_format': json['private_key_format'] == null ? undefined : json['private_key_format'],
        'remove_roots_from_chain': json['remove_roots_from_chain'] == null ? undefined : json['remove_roots_from_chain'],
        'serial_number': json['serial_number'] == null ? undefined : json['serial_number'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'uri_sans': json['uri_sans'] == null ? undefined : json['uri_sans'],
        'user_ids': json['user_ids'] == null ? undefined : json['user_ids'],
    };
}

export function PkiIssuerIssueWithRoleRequestToJSON(json: any): PkiIssuerIssueWithRoleRequest {
    return PkiIssuerIssueWithRoleRequestToJSONTyped(json, false);
}

export function PkiIssuerIssueWithRoleRequestToJSONTyped(value?: PkiIssuerIssueWithRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alt_names': value['alt_names'],
        'cert_metadata': value['cert_metadata'],
        'common_name': value['common_name'],
        'exclude_cn_from_sans': value['exclude_cn_from_sans'],
        'format': value['format'],
        'ip_sans': value['ip_sans'],
        'jks_alias': value['jks_alias'],
        'jks_password': value['jks_password'],
        'not_after': value['not_after'],
        'other_sans': value['other_sans'],
        'pkcs12_encoder': value['pkcs12_encoder'],
        'pkcs12_password': value['pkcs12_password'],
        'private_key_format': value['private_key_format'],
        'remove_roots_from_chain': value['remove_roots_from_chain'],
        'serial_number': value['serial_number'],
        'ttl': value['ttl'],
        'uri_sans': value['uri_sans'],
        'user_ids': value['user_ids'],
    };
}

