/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiReadCertDeltaCrlResponse
 */
export interface PkiReadCertDeltaCrlResponse {
    /**
     * Issuing CA Chain
     * @type {string}
     * @memberof PkiReadCertDeltaCrlResponse
     */
    ca_chain?: string;
    /**
     * Certificate
     * @type {string}
     * @memberof PkiReadCertDeltaCrlResponse
     */
    certificate?: string;
    /**
     * ID of the issuer
     * @type {string}
     * @memberof PkiReadCertDeltaCrlResponse
     */
    issuer_id?: string;
    /**
     * Revocation time
     * @type {number}
     * @memberof PkiReadCertDeltaCrlResponse
     */
    revocation_time?: number;
    /**
     * Revocation time RFC 3339 formatted
     * @type {string}
     * @memberof PkiReadCertDeltaCrlResponse
     */
    revocation_time_rfc3339?: string;
}

/**
 * Check if a given object implements the PkiReadCertDeltaCrlResponse interface.
 */
export function instanceOfPkiReadCertDeltaCrlResponse(value: object): value is PkiReadCertDeltaCrlResponse {
    return true;
}

export function PkiReadCertDeltaCrlResponseFromJSON(json: any): PkiReadCertDeltaCrlResponse {
    return PkiReadCertDeltaCrlResponseFromJSONTyped(json, false);
}

export function PkiReadCertDeltaCrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiReadCertDeltaCrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ca_chain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'issuer_id': json['issuer_id'] == null ? undefined : json['issuer_id'],
        'revocation_time': json['revocation_time'] == null ? undefined : json['revocation_time'],
        'revocation_time_rfc3339': json['revocation_time_rfc3339'] == null ? undefined : json['revocation_time_rfc3339'],
    };
}

export function PkiReadCertDeltaCrlResponseToJSON(json: any): PkiReadCertDeltaCrlResponse {
    return PkiReadCertDeltaCrlResponseToJSONTyped(json, false);
}

export function PkiReadCertDeltaCrlResponseToJSONTyped(value?: PkiReadCertDeltaCrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ca_chain': value['ca_chain'],
        'certificate': value['certificate'],
        'issuer_id': value['issuer_id'],
        'revocation_time': value['revocation_time'],
        'revocation_time_rfc3339': value['revocation_time_rfc3339'],
    };
}

