/**
 * Copyright IBM Corp. 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiReadIssuerPemResponse
 */
export interface PkiReadIssuerPemResponse {
    /**
     * CA Chain
     * @type {Array<string>}
     * @memberof PkiReadIssuerPemResponse
     */
    ca_chain?: Array<string>;
    /**
     * Certificate
     * @type {string}
     * @memberof PkiReadIssuerPemResponse
     */
    certificate?: string;
    /**
     * Issuer Id
     * @type {string}
     * @memberof PkiReadIssuerPemResponse
     */
    issuer_id?: string;
    /**
     * Issuer Name
     * @type {string}
     * @memberof PkiReadIssuerPemResponse
     */
    issuer_name?: string;
}

/**
 * Check if a given object implements the PkiReadIssuerPemResponse interface.
 */
export function instanceOfPkiReadIssuerPemResponse(value: object): value is PkiReadIssuerPemResponse {
    return true;
}

export function PkiReadIssuerPemResponseFromJSON(json: any): PkiReadIssuerPemResponse {
    return PkiReadIssuerPemResponseFromJSONTyped(json, false);
}

export function PkiReadIssuerPemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiReadIssuerPemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ca_chain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'issuer_id': json['issuer_id'] == null ? undefined : json['issuer_id'],
        'issuer_name': json['issuer_name'] == null ? undefined : json['issuer_name'],
    };
}

export function PkiReadIssuerPemResponseToJSON(json: any): PkiReadIssuerPemResponse {
    return PkiReadIssuerPemResponseToJSONTyped(json, false);
}

export function PkiReadIssuerPemResponseToJSONTyped(value?: PkiReadIssuerPemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ca_chain': value['ca_chain'],
        'certificate': value['certificate'],
        'issuer_id': value['issuer_id'],
        'issuer_name': value['issuer_name'],
    };
}

