/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteIssuerIssuerRefExportPrivateResponse
 */
export interface PkiWriteIssuerIssuerRefExportPrivateResponse {
    /**
     * CA Chain
     * @type {Array<string>}
     * @memberof PkiWriteIssuerIssuerRefExportPrivateResponse
     */
    ca_chain?: Array<string>;
    /**
     * Certificate
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExportPrivateResponse
     */
    certificate?: string;
    /**
     * Issuer Id
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExportPrivateResponse
     */
    issuer_id?: string;
    /**
     * Issuer Name
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExportPrivateResponse
     */
    issuer_name?: string;
    /**
     * CA Private Key encrypted by one or more provided PGP/GPG keys
     * @type {Array<string>}
     * @memberof PkiWriteIssuerIssuerRefExportPrivateResponse
     */
    private_key?: Array<string>;
}

/**
 * Check if a given object implements the PkiWriteIssuerIssuerRefExportPrivateResponse interface.
 */
export function instanceOfPkiWriteIssuerIssuerRefExportPrivateResponse(value: object): value is PkiWriteIssuerIssuerRefExportPrivateResponse {
    return true;
}

export function PkiWriteIssuerIssuerRefExportPrivateResponseFromJSON(json: any): PkiWriteIssuerIssuerRefExportPrivateResponse {
    return PkiWriteIssuerIssuerRefExportPrivateResponseFromJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExportPrivateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteIssuerIssuerRefExportPrivateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ca_chain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'issuer_id': json['issuer_id'] == null ? undefined : json['issuer_id'],
        'issuer_name': json['issuer_name'] == null ? undefined : json['issuer_name'],
        'private_key': json['private_key'] == null ? undefined : json['private_key'],
    };
}

export function PkiWriteIssuerIssuerRefExportPrivateResponseToJSON(json: any): PkiWriteIssuerIssuerRefExportPrivateResponse {
    return PkiWriteIssuerIssuerRefExportPrivateResponseToJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExportPrivateResponseToJSONTyped(value?: PkiWriteIssuerIssuerRefExportPrivateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ca_chain': value['ca_chain'],
        'certificate': value['certificate'],
        'issuer_id': value['issuer_id'],
        'issuer_name': value['issuer_name'],
        'private_key': value['private_key'],
    };
}

