/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteExternalPolicySignPolicyResponse
 */
export interface PkiWriteExternalPolicySignPolicyResponse {
    /**
     * Certificate Chain
     * @type {Array<string>}
     * @memberof PkiWriteExternalPolicySignPolicyResponse
     */
    ca_chain?: Array<string>;
    /**
     * Certificate
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyResponse
     */
    certificate?: string;
    /**
     * Time of expiration
     * @type {number}
     * @memberof PkiWriteExternalPolicySignPolicyResponse
     */
    expiration?: number;
    /**
     * Issuing Certificate Authority
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyResponse
     */
    issuing_ca?: string;
    /**
     * Serial Number
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyResponse
     */
    serial_number?: string;
}

/**
 * Check if a given object implements the PkiWriteExternalPolicySignPolicyResponse interface.
 */
export function instanceOfPkiWriteExternalPolicySignPolicyResponse(value: object): value is PkiWriteExternalPolicySignPolicyResponse {
    return true;
}

export function PkiWriteExternalPolicySignPolicyResponseFromJSON(json: any): PkiWriteExternalPolicySignPolicyResponse {
    return PkiWriteExternalPolicySignPolicyResponseFromJSONTyped(json, false);
}

export function PkiWriteExternalPolicySignPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteExternalPolicySignPolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ca_chain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'issuing_ca': json['issuing_ca'] == null ? undefined : json['issuing_ca'],
        'serial_number': json['serial_number'] == null ? undefined : json['serial_number'],
    };
}

export function PkiWriteExternalPolicySignPolicyResponseToJSON(json: any): PkiWriteExternalPolicySignPolicyResponse {
    return PkiWriteExternalPolicySignPolicyResponseToJSONTyped(json, false);
}

export function PkiWriteExternalPolicySignPolicyResponseToJSONTyped(value?: PkiWriteExternalPolicySignPolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ca_chain': value['ca_chain'],
        'certificate': value['certificate'],
        'expiration': value['expiration'],
        'issuing_ca': value['issuing_ca'],
        'serial_number': value['serial_number'],
    };
}

