/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteExternalPolicyIssueRequest
 */
export interface PkiWriteExternalPolicyIssueRequest {
    [key: string]: any | any;
    /**
     * Format for returned data. Can be "pem", "der", "pem_bundle", "pkcs12_bundle" or "jks_bundle". If "pem_bundle", any private key and issuing cert will be appended to the certificate pem. Formats "der", "pkcs12_bundle" or "jks_bundle" are base64 encoded. Defaults to "pem".
     * @type {string}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    format?: PkiWriteExternalPolicyIssueRequestFormatEnum;
    /**
     * Password for encrypting the Java keystore when format is set to "jks_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    jks_password?: string;
    /**
     * The entry alias in the Java keystore (JKS) when format is set to "jks_bundle" and bundle contains a single PrivateKeyEntry. This field is case-sensitive, but relying on case-only differences for unique aliases is not recommended. Defaults to "1". This parameter is ignored by endpoints that return TrustedCertificateEntry values (trust stores), and instead entries are assigned incrementing numeric strings aliases starting at "1".
     * @type {string}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    jks_private_key_alias?: string;
    /**
     * The number of bits to use. Allowed values are 0 (universal default); with rsa key_type: 2048 (default), 3072, or 4096; with ec key_type: 224, 256 (default), 384, or 521; ignored with ed25519.
     * @type {number}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    key_bits?: number;
    /**
     * The type of key to use; defaults to RSA. "rsa" "ec" and "ed25519" are the only valid values.
     * @type {string}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    key_type?: PkiWriteExternalPolicyIssueRequestKeyTypeEnum;
    /**
     * Encoder profile to use for PKCS#12 archives when format is set to "pkcs12_bundle". Valid values are "modern2026" and "modern2023". Defaults to "modern2026", which uses the newer PKCS#12 integrity format (PBMAC1).
     * @type {string}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    pkcs12_encoder?: PkiWriteExternalPolicyIssueRequestPkcs12EncoderEnum;
    /**
     * Password for encrypting the PKCS#12 archive when format is set to "pkcs12_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    pkcs12_password?: string;
    /**
     * Format for the returned private key. Generally the default will be controlled by the "format" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to "pkcs8" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to "der".
     * @type {string}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    private_key_format?: PkiWriteExternalPolicyIssueRequestPrivateKeyFormatEnum;
    /**
     * Whether or not to remove self-signed CA certificates in the output of the ca_chain field.
     * @type {boolean}
     * @memberof PkiWriteExternalPolicyIssueRequest
     */
    remove_roots_from_chain?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum PkiWriteExternalPolicyIssueRequestFormatEnum {
    PEM = 'pem',
    DER = 'der',
    PEM_BUNDLE = 'pem_bundle'
}
/**
* @export
* @enum {string}
*/
export enum PkiWriteExternalPolicyIssueRequestKeyTypeEnum {
    RSA = 'rsa',
    EC = 'ec',
    ED25519 = 'ed25519'
}
/**
* @export
* @enum {string}
*/
export enum PkiWriteExternalPolicyIssueRequestPkcs12EncoderEnum {
    MODERN2026 = 'modern2026',
    MODERN2023 = 'modern2023'
}
/**
* @export
* @enum {string}
*/
export enum PkiWriteExternalPolicyIssueRequestPrivateKeyFormatEnum {
    DER = 'der',
    PEM = 'pem',
    PKCS8 = 'pkcs8'
}


/**
 * Check if a given object implements the PkiWriteExternalPolicyIssueRequest interface.
 */
export function instanceOfPkiWriteExternalPolicyIssueRequest(value: object): value is PkiWriteExternalPolicyIssueRequest {
    return true;
}

export function PkiWriteExternalPolicyIssueRequestFromJSON(json: any): PkiWriteExternalPolicyIssueRequest {
    return PkiWriteExternalPolicyIssueRequestFromJSONTyped(json, false);
}

export function PkiWriteExternalPolicyIssueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteExternalPolicyIssueRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'format': json['format'] == null ? undefined : json['format'],
        'jks_password': json['jks_password'] == null ? undefined : json['jks_password'],
        'jks_private_key_alias': json['jks_private_key_alias'] == null ? undefined : json['jks_private_key_alias'],
        'key_bits': json['key_bits'] == null ? undefined : json['key_bits'],
        'key_type': json['key_type'] == null ? undefined : json['key_type'],
        'pkcs12_encoder': json['pkcs12_encoder'] == null ? undefined : json['pkcs12_encoder'],
        'pkcs12_password': json['pkcs12_password'] == null ? undefined : json['pkcs12_password'],
        'private_key_format': json['private_key_format'] == null ? undefined : json['private_key_format'],
        'remove_roots_from_chain': json['remove_roots_from_chain'] == null ? undefined : json['remove_roots_from_chain'],
    };
}

export function PkiWriteExternalPolicyIssueRequestToJSON(json: any): PkiWriteExternalPolicyIssueRequest {
    return PkiWriteExternalPolicyIssueRequestToJSONTyped(json, false);
}

export function PkiWriteExternalPolicyIssueRequestToJSONTyped(value?: PkiWriteExternalPolicyIssueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'format': value['format'],
        'jks_password': value['jks_password'],
        'jks_private_key_alias': value['jks_private_key_alias'],
        'key_bits': value['key_bits'],
        'key_type': value['key_type'],
        'pkcs12_encoder': value['pkcs12_encoder'],
        'pkcs12_password': value['pkcs12_password'],
        'private_key_format': value['private_key_format'],
        'remove_roots_from_chain': value['remove_roots_from_chain'],
    };
}

