/**
 * Copyright IBM Corp. 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteBatchCertsRequest
 */
export interface PkiWriteBatchCertsRequest {
    /**
     * Serial numbers of certificates to be read.
     * @type {Array<string>}
     * @memberof PkiWriteBatchCertsRequest
     */
    serial_numbers?: Array<string>;
}

/**
 * Check if a given object implements the PkiWriteBatchCertsRequest interface.
 */
export function instanceOfPkiWriteBatchCertsRequest(value: object): value is PkiWriteBatchCertsRequest {
    return true;
}

export function PkiWriteBatchCertsRequestFromJSON(json: any): PkiWriteBatchCertsRequest {
    return PkiWriteBatchCertsRequestFromJSONTyped(json, false);
}

export function PkiWriteBatchCertsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteBatchCertsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serial_numbers': json['serial_numbers'] == null ? undefined : json['serial_numbers'],
    };
}

export function PkiWriteBatchCertsRequestToJSON(json: any): PkiWriteBatchCertsRequest {
    return PkiWriteBatchCertsRequestToJSONTyped(json, false);
}

export function PkiWriteBatchCertsRequestToJSONTyped(value?: PkiWriteBatchCertsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serial_numbers': value['serial_numbers'],
    };
}

