/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest
 */
export interface PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest {
    [key: string]: any | any;
    /**
     * PEM-format CSR is expected but the contents of this field will not be validated
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest
     */
    csr: string;
    /**
     * Format for returned data. Can be "pem", "der", "pem_bundle", "pkcs12_bundle" or "jks_bundle". If "pem_bundle", any private key and issuing cert will be appended to the certificate pem. Formats "der", "pkcs12_bundle" or "jks_bundle" are base64 encoded. Defaults to "pem".
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest
     */
    format?: PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestFormatEnum;
    /**
     * Password for encrypting the Java keystore when format is set to "jks_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest
     */
    jks_password?: string;
    /**
     * Encoder profile to use for PKCS#12 archives when format is set to "pkcs12_bundle". Valid values are "modern2026" and "modern2023". Defaults to "modern2026", which uses the newer PKCS#12 integrity format (PBMAC1).
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest
     */
    pkcs12_encoder?: PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestPkcs12EncoderEnum;
    /**
     * Password for encrypting the PKCS#12 archive when format is set to "pkcs12_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest
     */
    pkcs12_password?: string;
}

/**
* @export
* @enum {string}
*/
export enum PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestFormatEnum {
    PEM = 'pem',
    DER = 'der',
    PEM_BUNDLE = 'pem_bundle'
}
/**
* @export
* @enum {string}
*/
export enum PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestPkcs12EncoderEnum {
    MODERN2026 = 'modern2026',
    MODERN2023 = 'modern2023'
}


/**
 * Check if a given object implements the PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest interface.
 */
export function instanceOfPkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest(value: object): value is PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest {
    if (!('csr' in value) || value['csr'] === undefined) return false;
    return true;
}

export function PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestFromJSON(json: any): PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest {
    return PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestFromJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'csr': json['csr'],
        'format': json['format'] == null ? undefined : json['format'],
        'jks_password': json['jks_password'] == null ? undefined : json['jks_password'],
        'pkcs12_encoder': json['pkcs12_encoder'] == null ? undefined : json['pkcs12_encoder'],
        'pkcs12_password': json['pkcs12_password'] == null ? undefined : json['pkcs12_password'],
    };
}

export function PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestToJSON(json: any): PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest {
    return PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestToJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequestToJSONTyped(value?: PkiWriteIssuerIssuerRefExternalPolicySignIntermediateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'csr': value['csr'],
        'format': value['format'],
        'jks_password': value['jks_password'],
        'pkcs12_encoder': value['pkcs12_encoder'],
        'pkcs12_password': value['pkcs12_password'],
    };
}

