/**
 * Copyright IBM Corp. 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteExternalPolicySignIntermediateResponse
 */
export interface PkiWriteExternalPolicySignIntermediateResponse {
    /**
     * Certificate Chain
     * @type {Array<string>}
     * @memberof PkiWriteExternalPolicySignIntermediateResponse
     */
    ca_chain?: Array<string>;
    /**
     * Certificate
     * @type {string}
     * @memberof PkiWriteExternalPolicySignIntermediateResponse
     */
    certificate?: string;
    /**
     * Time of expiration
     * @type {number}
     * @memberof PkiWriteExternalPolicySignIntermediateResponse
     */
    expiration?: number;
    /**
     * Issuing Certificate Authority
     * @type {string}
     * @memberof PkiWriteExternalPolicySignIntermediateResponse
     */
    issuing_ca?: string;
    /**
     * Serial Number
     * @type {string}
     * @memberof PkiWriteExternalPolicySignIntermediateResponse
     */
    serial_number?: string;
}

/**
 * Check if a given object implements the PkiWriteExternalPolicySignIntermediateResponse interface.
 */
export function instanceOfPkiWriteExternalPolicySignIntermediateResponse(value: object): value is PkiWriteExternalPolicySignIntermediateResponse {
    return true;
}

export function PkiWriteExternalPolicySignIntermediateResponseFromJSON(json: any): PkiWriteExternalPolicySignIntermediateResponse {
    return PkiWriteExternalPolicySignIntermediateResponseFromJSONTyped(json, false);
}

export function PkiWriteExternalPolicySignIntermediateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteExternalPolicySignIntermediateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ca_chain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'issuing_ca': json['issuing_ca'] == null ? undefined : json['issuing_ca'],
        'serial_number': json['serial_number'] == null ? undefined : json['serial_number'],
    };
}

export function PkiWriteExternalPolicySignIntermediateResponseToJSON(json: any): PkiWriteExternalPolicySignIntermediateResponse {
    return PkiWriteExternalPolicySignIntermediateResponseToJSONTyped(json, false);
}

export function PkiWriteExternalPolicySignIntermediateResponseToJSONTyped(value?: PkiWriteExternalPolicySignIntermediateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ca_chain': value['ca_chain'],
        'certificate': value['certificate'],
        'expiration': value['expiration'],
        'issuing_ca': value['issuing_ca'],
        'serial_number': value['serial_number'],
    };
}

