/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteIntegrationGuardiumRequest
 */
export interface PkiWriteIntegrationGuardiumRequest {
    /**
     * The URL a user should be taken to when clicking in the Vault UI
     * @type {string}
     * @memberof PkiWriteIntegrationGuardiumRequest
     */
    url: string;
}

/**
 * Check if a given object implements the PkiWriteIntegrationGuardiumRequest interface.
 */
export function instanceOfPkiWriteIntegrationGuardiumRequest(value: object): value is PkiWriteIntegrationGuardiumRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PkiWriteIntegrationGuardiumRequestFromJSON(json: any): PkiWriteIntegrationGuardiumRequest {
    return PkiWriteIntegrationGuardiumRequestFromJSONTyped(json, false);
}

export function PkiWriteIntegrationGuardiumRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteIntegrationGuardiumRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function PkiWriteIntegrationGuardiumRequestToJSON(json: any): PkiWriteIntegrationGuardiumRequest {
    return PkiWriteIntegrationGuardiumRequestToJSONTyped(json, false);
}

export function PkiWriteIntegrationGuardiumRequestToJSONTyped(value?: PkiWriteIntegrationGuardiumRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

