/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteExternalPolicySignPolicyRequest
 */
export interface PkiWriteExternalPolicySignPolicyRequest {
    [key: string]: any | any;
    /**
     * PEM-format CSR is expected but the contents of this field will not be validated
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyRequest
     */
    csr: string;
    /**
     * Format for returned data. Can be "pem", "der", "pem_bundle", "pkcs12_bundle" or "jks_bundle". If "pem_bundle", any private key and issuing cert will be appended to the certificate pem. Formats "der", "pkcs12_bundle" or "jks_bundle" are base64 encoded. Defaults to "pem".
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyRequest
     */
    format?: PkiWriteExternalPolicySignPolicyRequestFormatEnum;
    /**
     * The entry alias in the Java keystore (JKS) when format is set to "jks_bundle" and bundle contains a single PrivateKeyEntry. This field is case-sensitive, but relying on case-only differences for unique aliases is not recommended. Defaults to "1". This parameter is ignored by endpoints that return multiple TrustedCertificateEntry values (trust stores), and entry aliases are assigned incrementing numeric strings starting at "1".
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyRequest
     */
    jks_alias?: string;
    /**
     * Password for encrypting the Java keystore when format is set to "jks_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyRequest
     */
    jks_password?: string;
    /**
     * Encoder profile to use for PKCS#12 archives when format is set to "pkcs12_bundle". Valid values are "modern2026" and "modern2023". Defaults to "modern2026", which uses the newer PKCS#12 integrity format (PBMAC1).
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyRequest
     */
    pkcs12_encoder?: PkiWriteExternalPolicySignPolicyRequestPkcs12EncoderEnum;
    /**
     * Password for encrypting the PKCS#12 archive when format is set to "pkcs12_bundle". If not provided, defaults to "changeit". It is recommended to use the default password and protect the file using other means or use a high-entropy password.
     * @type {string}
     * @memberof PkiWriteExternalPolicySignPolicyRequest
     */
    pkcs12_password?: string;
    /**
     * Whether or not to remove self-signed CA certificates in the output of the ca_chain field.
     * @type {boolean}
     * @memberof PkiWriteExternalPolicySignPolicyRequest
     */
    remove_roots_from_chain?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum PkiWriteExternalPolicySignPolicyRequestFormatEnum {
    PEM = 'pem',
    DER = 'der',
    PEM_BUNDLE = 'pem_bundle'
}
/**
* @export
* @enum {string}
*/
export enum PkiWriteExternalPolicySignPolicyRequestPkcs12EncoderEnum {
    MODERN2026 = 'modern2026',
    MODERN2023 = 'modern2023'
}


/**
 * Check if a given object implements the PkiWriteExternalPolicySignPolicyRequest interface.
 */
export function instanceOfPkiWriteExternalPolicySignPolicyRequest(value: object): value is PkiWriteExternalPolicySignPolicyRequest {
    if (!('csr' in value) || value['csr'] === undefined) return false;
    return true;
}

export function PkiWriteExternalPolicySignPolicyRequestFromJSON(json: any): PkiWriteExternalPolicySignPolicyRequest {
    return PkiWriteExternalPolicySignPolicyRequestFromJSONTyped(json, false);
}

export function PkiWriteExternalPolicySignPolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteExternalPolicySignPolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'csr': json['csr'],
        'format': json['format'] == null ? undefined : json['format'],
        'jks_alias': json['jks_alias'] == null ? undefined : json['jks_alias'],
        'jks_password': json['jks_password'] == null ? undefined : json['jks_password'],
        'pkcs12_encoder': json['pkcs12_encoder'] == null ? undefined : json['pkcs12_encoder'],
        'pkcs12_password': json['pkcs12_password'] == null ? undefined : json['pkcs12_password'],
        'remove_roots_from_chain': json['remove_roots_from_chain'] == null ? undefined : json['remove_roots_from_chain'],
    };
}

export function PkiWriteExternalPolicySignPolicyRequestToJSON(json: any): PkiWriteExternalPolicySignPolicyRequest {
    return PkiWriteExternalPolicySignPolicyRequestToJSONTyped(json, false);
}

export function PkiWriteExternalPolicySignPolicyRequestToJSONTyped(value?: PkiWriteExternalPolicySignPolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'csr': value['csr'],
        'format': value['format'],
        'jks_alias': value['jks_alias'],
        'jks_password': value['jks_password'],
        'pkcs12_encoder': value['pkcs12_encoder'],
        'pkcs12_password': value['pkcs12_password'],
        'remove_roots_from_chain': value['remove_roots_from_chain'],
    };
}

