/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PoliciesReadRotationPolicyResponse
 */
export interface PoliciesReadRotationPolicyResponse {
    /**
     * The maximum number of retries per cycle allowed for rotation.
     * @type {number}
     * @memberof PoliciesReadRotationPolicyResponse
     */
    max_retries_per_cycle?: number;
    /**
     * The maximum number of retry cycles allowed for rotation.
     * @type {number}
     * @memberof PoliciesReadRotationPolicyResponse
     */
    max_retry_cycles?: number;
}

/**
 * Check if a given object implements the PoliciesReadRotationPolicyResponse interface.
 */
export function instanceOfPoliciesReadRotationPolicyResponse(value: object): value is PoliciesReadRotationPolicyResponse {
    return true;
}

export function PoliciesReadRotationPolicyResponseFromJSON(json: any): PoliciesReadRotationPolicyResponse {
    return PoliciesReadRotationPolicyResponseFromJSONTyped(json, false);
}

export function PoliciesReadRotationPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoliciesReadRotationPolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'max_retries_per_cycle': json['max_retries_per_cycle'] == null ? undefined : json['max_retries_per_cycle'],
        'max_retry_cycles': json['max_retry_cycles'] == null ? undefined : json['max_retry_cycles'],
    };
}

export function PoliciesReadRotationPolicyResponseToJSON(json: any): PoliciesReadRotationPolicyResponse {
    return PoliciesReadRotationPolicyResponseToJSONTyped(json, false);
}

export function PoliciesReadRotationPolicyResponseToJSONTyped(value?: PoliciesReadRotationPolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_retries_per_cycle': value['max_retries_per_cycle'],
        'max_retry_cycles': value['max_retry_cycles'],
    };
}

