/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PoliciesReadPasswordPolicyResponse
 */
export interface PoliciesReadPasswordPolicyResponse {
    /**
     * 
     * @type {string}
     * @memberof PoliciesReadPasswordPolicyResponse
     */
    entropy_source?: string;
    /**
     * 
     * @type {string}
     * @memberof PoliciesReadPasswordPolicyResponse
     */
    policy?: string;
}

/**
 * Check if a given object implements the PoliciesReadPasswordPolicyResponse interface.
 */
export function instanceOfPoliciesReadPasswordPolicyResponse(value: object): value is PoliciesReadPasswordPolicyResponse {
    return true;
}

export function PoliciesReadPasswordPolicyResponseFromJSON(json: any): PoliciesReadPasswordPolicyResponse {
    return PoliciesReadPasswordPolicyResponseFromJSONTyped(json, false);
}

export function PoliciesReadPasswordPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoliciesReadPasswordPolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entropy_source': json['entropy_source'] == null ? undefined : json['entropy_source'],
        'policy': json['policy'] == null ? undefined : json['policy'],
    };
}

export function PoliciesReadPasswordPolicyResponseToJSON(json: any): PoliciesReadPasswordPolicyResponse {
    return PoliciesReadPasswordPolicyResponseToJSONTyped(json, false);
}

export function PoliciesReadPasswordPolicyResponseToJSONTyped(value?: PoliciesReadPasswordPolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entropy_source': value['entropy_source'],
        'policy': value['policy'],
    };
}

