/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterCreateRequest
 */
export interface RegisterCreateRequest {
    /**
     * Human readable name of the registration.
     * @type {string}
     * @memberof RegisterCreateRequest
     */
    display_name: string;
    /**
     * Entity ID representing this agent.
     * @type {string}
     * @memberof RegisterCreateRequest
     */
    entity_id: string;
    /**
     * ID of the registration. If set, updates the corresponding existing registration.
     * @type {string}
     * @memberof RegisterCreateRequest
     */
    id?: string;
}

/**
 * Check if a given object implements the RegisterCreateRequest interface.
 */
export function instanceOfRegisterCreateRequest(value: object): value is RegisterCreateRequest {
    if (!('display_name' in value) || value['display_name'] === undefined) return false;
    if (!('entity_id' in value) || value['entity_id'] === undefined) return false;
    return true;
}

export function RegisterCreateRequestFromJSON(json: any): RegisterCreateRequest {
    return RegisterCreateRequestFromJSONTyped(json, false);
}

export function RegisterCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'display_name': json['display_name'],
        'entity_id': json['entity_id'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function RegisterCreateRequestToJSON(json: any): RegisterCreateRequest {
    return RegisterCreateRequestToJSONTyped(json, false);
}

export function RegisterCreateRequestToJSONTyped(value?: RegisterCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['display_name'],
        'entity_id': value['entity_id'],
        'id': value['id'],
    };
}

