/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RekeyRecoveryKeyVerificationReadProgressResponse
 */
export interface RekeyRecoveryKeyVerificationReadProgressResponse {
    /**
     * 
     * @type {number}
     * @memberof RekeyRecoveryKeyVerificationReadProgressResponse
     */
    n?: number;
    /**
     * 
     * @type {string}
     * @memberof RekeyRecoveryKeyVerificationReadProgressResponse
     */
    nonce?: string;
    /**
     * 
     * @type {number}
     * @memberof RekeyRecoveryKeyVerificationReadProgressResponse
     */
    progress?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RekeyRecoveryKeyVerificationReadProgressResponse
     */
    started?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RekeyRecoveryKeyVerificationReadProgressResponse
     */
    t?: number;
}

/**
 * Check if a given object implements the RekeyRecoveryKeyVerificationReadProgressResponse interface.
 */
export function instanceOfRekeyRecoveryKeyVerificationReadProgressResponse(value: object): value is RekeyRecoveryKeyVerificationReadProgressResponse {
    return true;
}

export function RekeyRecoveryKeyVerificationReadProgressResponseFromJSON(json: any): RekeyRecoveryKeyVerificationReadProgressResponse {
    return RekeyRecoveryKeyVerificationReadProgressResponseFromJSONTyped(json, false);
}

export function RekeyRecoveryKeyVerificationReadProgressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RekeyRecoveryKeyVerificationReadProgressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'n': json['n'] == null ? undefined : json['n'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'started': json['started'] == null ? undefined : json['started'],
        't': json['t'] == null ? undefined : json['t'],
    };
}

export function RekeyRecoveryKeyVerificationReadProgressResponseToJSON(json: any): RekeyRecoveryKeyVerificationReadProgressResponse {
    return RekeyRecoveryKeyVerificationReadProgressResponseToJSONTyped(json, false);
}

export function RekeyRecoveryKeyVerificationReadProgressResponseToJSONTyped(value?: RekeyRecoveryKeyVerificationReadProgressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'n': value['n'],
        'nonce': value['nonce'],
        'progress': value['progress'],
        'started': value['started'],
        't': value['t'],
    };
}

