/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SamlWriteTokenRequest
 */
export interface SamlWriteTokenRequest {
    /**
     * The value which produced the 'client_challenge' provided to the SSO Service URL API at the start of the authentication flow. Its base64-encoded, sha256 digest must match the 'client_challenge' value.
     * @type {string}
     * @memberof SamlWriteTokenRequest
     */
    client_verifier: string;
    /**
     * The 'token_poll_id' value returned from the SSO Service URL API at the start of the authentication flow.
     * @type {string}
     * @memberof SamlWriteTokenRequest
     */
    token_poll_id: string;
}

/**
 * Check if a given object implements the SamlWriteTokenRequest interface.
 */
export function instanceOfSamlWriteTokenRequest(value: object): value is SamlWriteTokenRequest {
    if (!('client_verifier' in value) || value['client_verifier'] === undefined) return false;
    if (!('token_poll_id' in value) || value['token_poll_id'] === undefined) return false;
    return true;
}

export function SamlWriteTokenRequestFromJSON(json: any): SamlWriteTokenRequest {
    return SamlWriteTokenRequestFromJSONTyped(json, false);
}

export function SamlWriteTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SamlWriteTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client_verifier': json['client_verifier'],
        'token_poll_id': json['token_poll_id'],
    };
}

export function SamlWriteTokenRequestToJSON(json: any): SamlWriteTokenRequest {
    return SamlWriteTokenRequestToJSONTyped(json, false);
}

export function SamlWriteTokenRequestToJSONTyped(value?: SamlWriteTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_verifier': value['client_verifier'],
        'token_poll_id': value['token_poll_id'],
    };
}

