/**
 * Copyright (c) HashiCorp, Inc.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpiffeConfigureRequest
 */
export interface SpiffeConfigureRequest {
    /**
     * The SPIFFE trust domain for this backend
     * @type {string}
     * @memberof SpiffeConfigureRequest
     */
    trust_domain?: string;
}

/**
 * Check if a given object implements the SpiffeConfigureRequest interface.
 */
export function instanceOfSpiffeConfigureRequest(value: object): value is SpiffeConfigureRequest {
    return true;
}

export function SpiffeConfigureRequestFromJSON(json: any): SpiffeConfigureRequest {
    return SpiffeConfigureRequestFromJSONTyped(json, false);
}

export function SpiffeConfigureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpiffeConfigureRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'trust_domain': json['trust_domain'] == null ? undefined : json['trust_domain'],
    };
}

export function SpiffeConfigureRequestToJSON(json: any): SpiffeConfigureRequest {
    return SpiffeConfigureRequestToJSONTyped(json, false);
}

export function SpiffeConfigureRequestToJSONTyped(value?: SpiffeConfigureRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trust_domain': value['trust_domain'],
    };
}

