/**
 * Copyright (c) HashiCorp, Inc.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemPatchSyncDestinationsInMemNameResponse
 */
export interface SystemPatchSyncDestinationsInMemNameResponse {
    /**
     * List of key value pairs of information necessary to connect with the external system.
     * @type {object}
     * @memberof SystemPatchSyncDestinationsInMemNameResponse
     */
    connection_details?: object;
    /**
     * Name of this secrets store.
     * @type {string}
     * @memberof SystemPatchSyncDestinationsInMemNameResponse
     */
    name?: string;
    /**
     * List of key value pairs of Vault configuration options.
     * @type {object}
     * @memberof SystemPatchSyncDestinationsInMemNameResponse
     */
    options?: object;
    /**
     * Error message if the purge job failed.
     * @type {string}
     * @memberof SystemPatchSyncDestinationsInMemNameResponse
     */
    purge_error?: string;
    /**
     * Timestamp of when a purge job was initiated when deleting a destination.
     * @type {Date}
     * @memberof SystemPatchSyncDestinationsInMemNameResponse
     */
    purge_initiated_at?: Date;
    /**
     * Type of this secrets store.
     * @type {string}
     * @memberof SystemPatchSyncDestinationsInMemNameResponse
     */
    type?: string;
}

/**
 * Check if a given object implements the SystemPatchSyncDestinationsInMemNameResponse interface.
 */
export function instanceOfSystemPatchSyncDestinationsInMemNameResponse(value: object): value is SystemPatchSyncDestinationsInMemNameResponse {
    return true;
}

export function SystemPatchSyncDestinationsInMemNameResponseFromJSON(json: any): SystemPatchSyncDestinationsInMemNameResponse {
    return SystemPatchSyncDestinationsInMemNameResponseFromJSONTyped(json, false);
}

export function SystemPatchSyncDestinationsInMemNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemPatchSyncDestinationsInMemNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connection_details': json['connection_details'] == null ? undefined : json['connection_details'],
        'name': json['name'] == null ? undefined : json['name'],
        'options': json['options'] == null ? undefined : json['options'],
        'purge_error': json['purge_error'] == null ? undefined : json['purge_error'],
        'purge_initiated_at': json['purge_initiated_at'] == null ? undefined : (new Date(json['purge_initiated_at'])),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SystemPatchSyncDestinationsInMemNameResponseToJSON(json: any): SystemPatchSyncDestinationsInMemNameResponse {
    return SystemPatchSyncDestinationsInMemNameResponseToJSONTyped(json, false);
}

export function SystemPatchSyncDestinationsInMemNameResponseToJSONTyped(value?: SystemPatchSyncDestinationsInMemNameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_details': value['connection_details'],
        'name': value['name'],
        'options': value['options'],
        'purge_error': value['purge_error'],
        'purge_initiated_at': value['purge_initiated_at'] == null ? undefined : ((value['purge_initiated_at']).toISOString()),
        'type': value['type'],
    };
}

