/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWriteBillingConfigRequest
 */
export interface SystemWriteBillingConfigRequest {
    /**
     * Number of months to retain billing data. Must be between 13 and 72 months. Defaults to 37 months.
     * @type {number}
     * @memberof SystemWriteBillingConfigRequest
     */
    retention_months?: number;
}

/**
 * Check if a given object implements the SystemWriteBillingConfigRequest interface.
 */
export function instanceOfSystemWriteBillingConfigRequest(value: object): value is SystemWriteBillingConfigRequest {
    return true;
}

export function SystemWriteBillingConfigRequestFromJSON(json: any): SystemWriteBillingConfigRequest {
    return SystemWriteBillingConfigRequestFromJSONTyped(json, false);
}

export function SystemWriteBillingConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWriteBillingConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'retention_months': json['retention_months'] == null ? undefined : json['retention_months'],
    };
}

export function SystemWriteBillingConfigRequestToJSON(json: any): SystemWriteBillingConfigRequest {
    return SystemWriteBillingConfigRequestToJSONTyped(json, false);
}

export function SystemWriteBillingConfigRequestToJSONTyped(value?: SystemWriteBillingConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'retention_months': value['retention_months'],
    };
}

