/**
 * Copyright (c) HashiCorp, Inc.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWriteStorageRaftSnapshotLoadResponse
 */
export interface SystemWriteStorageRaftSnapshotLoadResponse {
    /**
     * name of auto-snapshot config
     * @type {string}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    auto_snapshot_config?: string;
    /**
     * the id of the cluster
     * @type {string}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    cluster_id?: string;
    /**
     * error message if status is error
     * @type {string}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    error?: string;
    /**
     * time when the snapshot expires and is removed
     * @type {Date}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    expires_at?: Date;
    /**
     * unique id of the snapshot
     * @type {string}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    snapshot_id?: string;
    /**
     * status of the snapshot, can be one of: loading, ready, error
     * @type {string}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    status?: string;
    /**
     * the entity id of the uploader
     * @type {string}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    uploader_entity_id?: string;
    /**
     * unique id of the snapshot
     * @type {string}
     * @memberof SystemWriteStorageRaftSnapshotLoadResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the SystemWriteStorageRaftSnapshotLoadResponse interface.
 */
export function instanceOfSystemWriteStorageRaftSnapshotLoadResponse(value: object): value is SystemWriteStorageRaftSnapshotLoadResponse {
    return true;
}

export function SystemWriteStorageRaftSnapshotLoadResponseFromJSON(json: any): SystemWriteStorageRaftSnapshotLoadResponse {
    return SystemWriteStorageRaftSnapshotLoadResponseFromJSONTyped(json, false);
}

export function SystemWriteStorageRaftSnapshotLoadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWriteStorageRaftSnapshotLoadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'auto_snapshot_config': json['auto_snapshot_config'] == null ? undefined : json['auto_snapshot_config'],
        'cluster_id': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'expires_at': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'snapshot_id': json['snapshot_id'] == null ? undefined : json['snapshot_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'uploader_entity_id': json['uploader_entity_id'] == null ? undefined : json['uploader_entity_id'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function SystemWriteStorageRaftSnapshotLoadResponseToJSON(json: any): SystemWriteStorageRaftSnapshotLoadResponse {
    return SystemWriteStorageRaftSnapshotLoadResponseToJSONTyped(json, false);
}

export function SystemWriteStorageRaftSnapshotLoadResponseToJSONTyped(value?: SystemWriteStorageRaftSnapshotLoadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auto_snapshot_config': value['auto_snapshot_config'],
        'cluster_id': value['cluster_id'],
        'error': value['error'],
        'expires_at': value['expires_at'] == null ? undefined : ((value['expires_at']).toISOString()),
        'snapshot_id': value['snapshot_id'],
        'status': value['status'],
        'uploader_entity_id': value['uploader_entity_id'],
        'url': value['url'],
    };
}

