/**
 * Copyright IBM Corp. 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWriteSyncDestinationsAwsSmNameRequest
 */
export interface SystemWriteSyncDestinationsAwsSmNameRequest {
    /**
     * AWS access key ID to access the secrets manager.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    access_key_id?: string;
    /**
     * Sets which IPv4 addresses Vault is allowed to connect to for syncing secrets.
     * @type {Array<string>}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    allowed_ipv4_addresses?: Array<string>;
    /**
     * Sets which IPv6 addresses Vault is allowed to connect to for syncing secrets.
     * @type {Array<string>}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    allowed_ipv6_addresses?: Array<string>;
    /**
     * Sets which port numbers Vault is allowed to connect through for syncing secrets.
     * @type {Array<string>}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    allowed_ports?: Array<string>;
    /**
     * Custom tags to set on the secret managed at the destination. Custom tags are merged with system tags.
     * @type {object}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    custom_tags?: object;
    /**
     * Allows all IP addresses and ports to be connected to for syncing secrets.
     * @type {boolean}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    disable_strict_networking?: boolean;
    /**
     * Unique string used as a condition for extra security when assuming the AWS IAM role. Optional. Ignored if the role ARN is not set.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    external_id?: string;
    /**
     * Force deletes destination without trying to unsync secrets from the destination.
     * @type {boolean}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    force_delete?: boolean;
    /**
     * Determines what level of information is synced as a distinct resource at the destination. Supports `secret-path` and `secret-key`.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    granularity?: string;
    /**
     * Asynchronously unsyncs all associated secrets with the destination then deletes the destination config.
     * @type {boolean}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    purge?: boolean;
    /**
     * AWS region where to manage secrets.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    region?: string;
    /**
     * AWS IAM role identifier Vault will assume when connecting to the Secrets Manager. Optional. Supports cross-account access.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    role_arn?: string;
    /**
     * AWS secret access key to access the secrets manager.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    secret_access_key?: string;
    /**
     * Template describing how to generate external secret names. Supports a subset of the Go Template syntax.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    secret_name_template?: string;
    /**
     * List of custom tags to remove for patch requests. This field is ignored on create and update requests.
     * @type {Array<string>}
     * @memberof SystemWriteSyncDestinationsAwsSmNameRequest
     */
    tags_to_remove?: Array<string>;
}

/**
 * Check if a given object implements the SystemWriteSyncDestinationsAwsSmNameRequest interface.
 */
export function instanceOfSystemWriteSyncDestinationsAwsSmNameRequest(value: object): value is SystemWriteSyncDestinationsAwsSmNameRequest {
    return true;
}

export function SystemWriteSyncDestinationsAwsSmNameRequestFromJSON(json: any): SystemWriteSyncDestinationsAwsSmNameRequest {
    return SystemWriteSyncDestinationsAwsSmNameRequestFromJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsAwsSmNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWriteSyncDestinationsAwsSmNameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'access_key_id': json['access_key_id'] == null ? undefined : json['access_key_id'],
        'allowed_ipv4_addresses': json['allowed_ipv4_addresses'] == null ? undefined : json['allowed_ipv4_addresses'],
        'allowed_ipv6_addresses': json['allowed_ipv6_addresses'] == null ? undefined : json['allowed_ipv6_addresses'],
        'allowed_ports': json['allowed_ports'] == null ? undefined : json['allowed_ports'],
        'custom_tags': json['custom_tags'] == null ? undefined : json['custom_tags'],
        'disable_strict_networking': json['disable_strict_networking'] == null ? undefined : json['disable_strict_networking'],
        'external_id': json['external_id'] == null ? undefined : json['external_id'],
        'force_delete': json['force_delete'] == null ? undefined : json['force_delete'],
        'granularity': json['granularity'] == null ? undefined : json['granularity'],
        'purge': json['purge'] == null ? undefined : json['purge'],
        'region': json['region'] == null ? undefined : json['region'],
        'role_arn': json['role_arn'] == null ? undefined : json['role_arn'],
        'secret_access_key': json['secret_access_key'] == null ? undefined : json['secret_access_key'],
        'secret_name_template': json['secret_name_template'] == null ? undefined : json['secret_name_template'],
        'tags_to_remove': json['tags_to_remove'] == null ? undefined : json['tags_to_remove'],
    };
}

export function SystemWriteSyncDestinationsAwsSmNameRequestToJSON(json: any): SystemWriteSyncDestinationsAwsSmNameRequest {
    return SystemWriteSyncDestinationsAwsSmNameRequestToJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsAwsSmNameRequestToJSONTyped(value?: SystemWriteSyncDestinationsAwsSmNameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key_id': value['access_key_id'],
        'allowed_ipv4_addresses': value['allowed_ipv4_addresses'],
        'allowed_ipv6_addresses': value['allowed_ipv6_addresses'],
        'allowed_ports': value['allowed_ports'],
        'custom_tags': value['custom_tags'],
        'disable_strict_networking': value['disable_strict_networking'],
        'external_id': value['external_id'],
        'force_delete': value['force_delete'],
        'granularity': value['granularity'],
        'purge': value['purge'],
        'region': value['region'],
        'role_arn': value['role_arn'],
        'secret_access_key': value['secret_access_key'],
        'secret_name_template': value['secret_name_template'],
        'tags_to_remove': value['tags_to_remove'],
    };
}

