/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TpmUpdateByIdRequest
 */
export interface TpmUpdateByIdRequest {
    /**
     * Whether the TPM is disabled.
     * @type {boolean}
     * @memberof TpmUpdateByIdRequest
     */
    disabled?: boolean;
    /**
     * Metadata to be associated with the TPM record. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: vault <command> <path> metadata=key1=value1 metadata=key2=value2
     * @type {object}
     * @memberof TpmUpdateByIdRequest
     */
    metadata?: object;
    /**
     * Name of the TPM record.
     * @type {string}
     * @memberof TpmUpdateByIdRequest
     */
    name?: string;
    /**
     * PEM-encoded TPM Endorsement Key (EK) public key.
     * @type {string}
     * @memberof TpmUpdateByIdRequest
     */
    tpm_ek_public_key?: string;
}

/**
 * Check if a given object implements the TpmUpdateByIdRequest interface.
 */
export function instanceOfTpmUpdateByIdRequest(value: object): value is TpmUpdateByIdRequest {
    return true;
}

export function TpmUpdateByIdRequestFromJSON(json: any): TpmUpdateByIdRequest {
    return TpmUpdateByIdRequestFromJSONTyped(json, false);
}

export function TpmUpdateByIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TpmUpdateByIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'tpm_ek_public_key': json['tpm_ek_public_key'] == null ? undefined : json['tpm_ek_public_key'],
    };
}

export function TpmUpdateByIdRequestToJSON(json: any): TpmUpdateByIdRequest {
    return TpmUpdateByIdRequestToJSONTyped(json, false);
}

export function TpmUpdateByIdRequestToJSONTyped(value?: TpmUpdateByIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disabled': value['disabled'],
        'metadata': value['metadata'],
        'name': value['name'],
        'tpm_ek_public_key': value['tpm_ek_public_key'],
    };
}

