/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TpmUpdateByNameRequest
 */
export interface TpmUpdateByNameRequest {
    /**
     * Whether the TPM is disabled.
     * @type {boolean}
     * @memberof TpmUpdateByNameRequest
     */
    disabled?: boolean;
    /**
     * ID of the TPM record. If set, updates the corresponding existing TPM.
     * @type {string}
     * @memberof TpmUpdateByNameRequest
     */
    id?: string;
    /**
     * Metadata to be associated with the TPM record. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: vault <command> <path> metadata=key1=value1 metadata=key2=value2
     * @type {object}
     * @memberof TpmUpdateByNameRequest
     */
    metadata?: object;
    /**
     * PEM-encoded TPM Endorsement Key (EK) public key.
     * @type {string}
     * @memberof TpmUpdateByNameRequest
     */
    tpm_ek_public_key?: string;
}

/**
 * Check if a given object implements the TpmUpdateByNameRequest interface.
 */
export function instanceOfTpmUpdateByNameRequest(value: object): value is TpmUpdateByNameRequest {
    return true;
}

export function TpmUpdateByNameRequestFromJSON(json: any): TpmUpdateByNameRequest {
    return TpmUpdateByNameRequestFromJSONTyped(json, false);
}

export function TpmUpdateByNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TpmUpdateByNameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'id': json['id'] == null ? undefined : json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'tpm_ek_public_key': json['tpm_ek_public_key'] == null ? undefined : json['tpm_ek_public_key'],
    };
}

export function TpmUpdateByNameRequestToJSON(json: any): TpmUpdateByNameRequest {
    return TpmUpdateByNameRequestToJSONTyped(json, false);
}

export function TpmUpdateByNameRequestToJSONTyped(value?: TpmUpdateByNameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disabled': value['disabled'],
        'id': value['id'],
        'metadata': value['metadata'],
        'tpm_ek_public_key': value['tpm_ek_public_key'],
    };
}

