/**
 * Copyright IBM Corp. 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransitGenerateDerivedkeysRequest
 */
export interface TransitGenerateDerivedkeysRequest {
    /**
     * Number of bits for the key; currently 128, 256, and 512 bits are supported. Defaults to 256.
     * @type {number}
     * @memberof TransitGenerateDerivedkeysRequest
     */
    bits?: number;
    /**
     * The info string input to derivation
     * @type {string}
     * @memberof TransitGenerateDerivedkeysRequest
     */
    info?: string;
    /**
     * The starting index for keys to return
     * @type {number}
     * @memberof TransitGenerateDerivedkeysRequest
     */
    key_index_from?: number;
    /**
     * The ending index (non-inclusive) for keys to return
     * @type {number}
     * @memberof TransitGenerateDerivedkeysRequest
     */
    key_index_to?: number;
    /**
     * The version of the Vault key to use for encryption of the data key. Must be 0 (for latest) or a value greater than or equal to the min_encryption_version configured on the key.
     * @type {number}
     * @memberof TransitGenerateDerivedkeysRequest
     */
    key_version?: number;
    /**
     * The salt input to derivation
     * @type {string}
     * @memberof TransitGenerateDerivedkeysRequest
     */
    salt?: string;
}

/**
 * Check if a given object implements the TransitGenerateDerivedkeysRequest interface.
 */
export function instanceOfTransitGenerateDerivedkeysRequest(value: object): value is TransitGenerateDerivedkeysRequest {
    return true;
}

export function TransitGenerateDerivedkeysRequestFromJSON(json: any): TransitGenerateDerivedkeysRequest {
    return TransitGenerateDerivedkeysRequestFromJSONTyped(json, false);
}

export function TransitGenerateDerivedkeysRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitGenerateDerivedkeysRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bits': json['bits'] == null ? undefined : json['bits'],
        'info': json['info'] == null ? undefined : json['info'],
        'key_index_from': json['key_index_from'] == null ? undefined : json['key_index_from'],
        'key_index_to': json['key_index_to'] == null ? undefined : json['key_index_to'],
        'key_version': json['key_version'] == null ? undefined : json['key_version'],
        'salt': json['salt'] == null ? undefined : json['salt'],
    };
}

export function TransitGenerateDerivedkeysRequestToJSON(json: any): TransitGenerateDerivedkeysRequest {
    return TransitGenerateDerivedkeysRequestToJSONTyped(json, false);
}

export function TransitGenerateDerivedkeysRequestToJSONTyped(value?: TransitGenerateDerivedkeysRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bits': value['bits'],
        'info': value['info'],
        'key_index_from': value['key_index_from'],
        'key_index_to': value['key_index_to'],
        'key_version': value['key_version'],
        'salt': value['salt'],
    };
}

