/**
 * Copyright IBM Corp. 2025, 2026
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransitChangeKeyAlgorithmRequest
 */
export interface TransitChangeKeyAlgorithmRequest {
    /**
     * The elliptic curve algorithm to use for hybrid signatures. Supported values: ecdsa-p256, ecdsa-p384, ecdsa-p521, ed25519.
     * @type {string}
     * @memberof TransitChangeKeyAlgorithmRequest
     */
    hybrid_key_type_ec?: string;
    /**
     * The post-quantum algorithm to use for hybrid signatures. Currently only ml-dsa is supported.
     * @type {string}
     * @memberof TransitChangeKeyAlgorithmRequest
     */
    hybrid_key_type_pqc?: string;
    /**
     * The key size in bytes for algorithms with variable key sizes. Currently only applicable to HMAC; must be between 32 and 512 bytes.
     * @type {number}
     * @memberof TransitChangeKeyAlgorithmRequest
     */
    key_size?: number;
    /**
     * The UUID of the managed key to use for this transit key.
     * @type {string}
     * @memberof TransitChangeKeyAlgorithmRequest
     */
    managed_key_id?: string;
    /**
     * The name of the managed key to use for this transit key.
     * @type {string}
     * @memberof TransitChangeKeyAlgorithmRequest
     */
    managed_key_name?: string;
    /**
     * The parameter set to use for ML-DSA or SLH-DSA. Required for ML-DSA, SLH-DSA, and hybrid keys.
     * @type {string}
     * @memberof TransitChangeKeyAlgorithmRequest
     */
    parameter_set?: string;
    /**
     * The new key type to use for future key versions. The currently-supported types are: aes128-gcm96, aes256-gcm96, chacha20-poly1305, ed25519, ecdsa-p256, ecdsa-p384, ecdsa-p521, rsa-2048, rsa-3072, rsa-4096, hmac, managed_key, aes128-cmac, aes192-cmac, aes256-cmac, ml-dsa, hybrid, slh-dsa, aes128-cbc, aes256-cbc.
     * @type {string}
     * @memberof TransitChangeKeyAlgorithmRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the TransitChangeKeyAlgorithmRequest interface.
 */
export function instanceOfTransitChangeKeyAlgorithmRequest(value: object): value is TransitChangeKeyAlgorithmRequest {
    return true;
}

export function TransitChangeKeyAlgorithmRequestFromJSON(json: any): TransitChangeKeyAlgorithmRequest {
    return TransitChangeKeyAlgorithmRequestFromJSONTyped(json, false);
}

export function TransitChangeKeyAlgorithmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitChangeKeyAlgorithmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hybrid_key_type_ec': json['hybrid_key_type_ec'] == null ? undefined : json['hybrid_key_type_ec'],
        'hybrid_key_type_pqc': json['hybrid_key_type_pqc'] == null ? undefined : json['hybrid_key_type_pqc'],
        'key_size': json['key_size'] == null ? undefined : json['key_size'],
        'managed_key_id': json['managed_key_id'] == null ? undefined : json['managed_key_id'],
        'managed_key_name': json['managed_key_name'] == null ? undefined : json['managed_key_name'],
        'parameter_set': json['parameter_set'] == null ? undefined : json['parameter_set'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TransitChangeKeyAlgorithmRequestToJSON(json: any): TransitChangeKeyAlgorithmRequest {
    return TransitChangeKeyAlgorithmRequestToJSONTyped(json, false);
}

export function TransitChangeKeyAlgorithmRequestToJSONTyped(value?: TransitChangeKeyAlgorithmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hybrid_key_type_ec': value['hybrid_key_type_ec'],
        'hybrid_key_type_pqc': value['hybrid_key_type_pqc'],
        'key_size': value['key_size'],
        'managed_key_id': value['managed_key_id'],
        'managed_key_name': value['managed_key_name'],
        'parameter_set': value['parameter_set'],
        'type': value['type'],
    };
}

