/**
 * Copyright IBM Corp. 2025
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransformWriteStoreRequest
 */
export interface TransformWriteStoreRequest {
    /**
     * For the `sql` store type, the templated connection string of the database.
     * @type {string}
     * @memberof TransformWriteStoreRequest
     */
    connection_string?: string;
    /**
     * For the `sql` store type, the database driver (database type) to use.
     * @type {string}
     * @memberof TransformWriteStoreRequest
     */
    driver?: string;
    /**
     * For the `sql` store type, the maximum duration a connection may remain open.
     * @type {number}
     * @memberof TransformWriteStoreRequest
     */
    max_connection_lifetime?: number;
    /**
     * For the `sql` store type, the maximum number of idle connections allowed to the database, 0 for default.
     * @type {number}
     * @memberof TransformWriteStoreRequest
     */
    max_idle_connections?: number;
    /**
     * For the `sql` store type, the maximum number of open connections allowed to the database, 0 for default.
     * @type {number}
     * @memberof TransformWriteStoreRequest
     */
    max_open_connections?: number;
    /**
     * For the `sql` store type, the password to use in populating the connection string.
     * @type {string}
     * @memberof TransformWriteStoreRequest
     */
    password?: string;
    /**
     * For the `sql` store type and databases which support multiple schemas, the schema in which to expect to find the storage tables.
     * @type {string}
     * @memberof TransformWriteStoreRequest
     */
    schema?: string;
    /**
     * Specifies a list of transformations this store supports. Currently only tokenization produces state needing storage.
     * @type {Array<string>}
     * @memberof TransformWriteStoreRequest
     */
    supported_transformations?: Array<string>;
    /**
     * Specifies the type of the store.
     * @type {string}
     * @memberof TransformWriteStoreRequest
     */
    type?: string;
    /**
     * For the `sql` store type, the username to use in populating the connection string.
     * @type {string}
     * @memberof TransformWriteStoreRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the TransformWriteStoreRequest interface.
 */
export function instanceOfTransformWriteStoreRequest(value: object): value is TransformWriteStoreRequest {
    return true;
}

export function TransformWriteStoreRequestFromJSON(json: any): TransformWriteStoreRequest {
    return TransformWriteStoreRequestFromJSONTyped(json, false);
}

export function TransformWriteStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransformWriteStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'connection_string': json['connection_string'] == null ? undefined : json['connection_string'],
        'driver': json['driver'] == null ? undefined : json['driver'],
        'max_connection_lifetime': json['max_connection_lifetime'] == null ? undefined : json['max_connection_lifetime'],
        'max_idle_connections': json['max_idle_connections'] == null ? undefined : json['max_idle_connections'],
        'max_open_connections': json['max_open_connections'] == null ? undefined : json['max_open_connections'],
        'password': json['password'] == null ? undefined : json['password'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'supported_transformations': json['supported_transformations'] == null ? undefined : json['supported_transformations'],
        'type': json['type'] == null ? undefined : json['type'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function TransformWriteStoreRequestToJSON(json: any): TransformWriteStoreRequest {
    return TransformWriteStoreRequestToJSONTyped(json, false);
}

export function TransformWriteStoreRequestToJSONTyped(value?: TransformWriteStoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_string': value['connection_string'],
        'driver': value['driver'],
        'max_connection_lifetime': value['max_connection_lifetime'],
        'max_idle_connections': value['max_idle_connections'],
        'max_open_connections': value['max_open_connections'],
        'password': value['password'],
        'schema': value['schema'],
        'supported_transformations': value['supported_transformations'],
        'type': value['type'],
        'username': value['username'],
    };
}

