/**
 * Copyright (c) HashiCorp, Inc.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UiLoginDefaultAuthConfigureRequest
 */
export interface UiLoginDefaultAuthConfigureRequest {
    /**
     * List of backup Auth method types to be shown in "Other Methods".
     * @type {Array<string>}
     * @memberof UiLoginDefaultAuthConfigureRequest
     */
    backup_auth_types?: Array<string>;
    /**
     * Preferred Auth method type for UI Login form.
     * @type {string}
     * @memberof UiLoginDefaultAuthConfigureRequest
     */
    default_auth_type: string;
    /**
     * Disable child namespaces from inheriting default auth type.
     * @type {boolean}
     * @memberof UiLoginDefaultAuthConfigureRequest
     */
    disable_inheritance?: boolean;
    /**
     * Namespace to apply default Auth method to.
     * @type {string}
     * @memberof UiLoginDefaultAuthConfigureRequest
     */
    namespace_path: string;
}

/**
 * Check if a given object implements the UiLoginDefaultAuthConfigureRequest interface.
 */
export function instanceOfUiLoginDefaultAuthConfigureRequest(value: object): value is UiLoginDefaultAuthConfigureRequest {
    if (!('default_auth_type' in value) || value['default_auth_type'] === undefined) return false;
    if (!('namespace_path' in value) || value['namespace_path'] === undefined) return false;
    return true;
}

export function UiLoginDefaultAuthConfigureRequestFromJSON(json: any): UiLoginDefaultAuthConfigureRequest {
    return UiLoginDefaultAuthConfigureRequestFromJSONTyped(json, false);
}

export function UiLoginDefaultAuthConfigureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UiLoginDefaultAuthConfigureRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'backup_auth_types': json['backup_auth_types'] == null ? undefined : json['backup_auth_types'],
        'default_auth_type': json['default_auth_type'],
        'disable_inheritance': json['disable_inheritance'] == null ? undefined : json['disable_inheritance'],
        'namespace_path': json['namespace_path'],
    };
}

export function UiLoginDefaultAuthConfigureRequestToJSON(json: any): UiLoginDefaultAuthConfigureRequest {
    return UiLoginDefaultAuthConfigureRequestToJSONTyped(json, false);
}

export function UiLoginDefaultAuthConfigureRequestToJSONTyped(value?: UiLoginDefaultAuthConfigureRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backup_auth_types': value['backup_auth_types'],
        'default_auth_type': value['default_auth_type'],
        'disable_inheritance': value['disable_inheritance'],
        'namespace_path': value['namespace_path'],
    };
}

