name: Generate Client

on: pull_request

jobs:
  generate-client:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Diff openapi.json with main
        run: |
          git fetch origin main
          if git diff --quiet origin/main -- ./openapi.json; then
            echo "::notice::No changes in openapi.json compared to main. Exiting workflow."
            exit 0
          fi

      - uses: ./.github/actions/setup-node

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Generate client
        run: yarn gen-client

      - uses: ./.github/actions/commit-changes
