name: Lint

on:
  workflow_run:
    workflows: [Generate Client]
    types:
      - completed

jobs:
  lint-ts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup-node

      - name: Type-check ts files
        run: yarn lint
