name: Spec Dispatch Receiver

on:
  repository_dispatch:
    types: [spec-change]

jobs:
  receive_spec:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4

      - name: Download Artifact from Vault Enterprise Repo
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #v8
        with:
          artifact-ids: ${{ github.event.client_payload.artifact_id }}
          run-id: ${{ github.event.client_payload.run_id }}
          github-token: ${{ secrets.SPEC_AUTOMATION_TOKEN }}
          repository: hashicorp/vault-enterprise

      - name: Commit and Create PR on External Repo
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 #v8
        with:
          branch: automated-spec-update-${{ github.run_id }}
          title: "[Automated] Updated OpenAPI Spec from Vault Enterprise"
          body: |
            This is an automated PR synced from the Vault Enterprise repository.
            The OpenAPI specification has been updated and the client should be regenerated.
          commit-message: "auto: openapi spec update"
          base: main
          labels: automated-spec-update
